<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>R统计绘图-线性混合效应模型详解(理论、模型构建、检验、选择、方差分解及结果可视化) - 编程大咖</title>
	<script>(function(d,e){d[e]=d[e].replace("no-js","js");})(document.documentElement,"className");</script>
	<meta name="description" content="">
		<meta property="og:url" content="https://bcdaka.github.io/posts/c902dc8566cfc4a56c627e1570e0a56f/">
  <meta property="og:site_name" content="编程大咖">
  <meta property="og:title" content="R统计绘图-线性混合效应模型详解(理论、模型构建、检验、选择、方差分解及结果可视化)">
  <meta property="og:description" content="目录
一、 基础理论
二、数据准备
三、构建线性混合效应模型(LMMs)
3.1 lme4线性混合效应模型formula
3.2 随机截距模型构建及检验
3.3 随机截距模型分析结果解释及可视化
3.4 随机斜率模型构建、检验及可视化
四、线性混合效应模型选择
4.1 多模型比较
4.2 模型最优子集筛选
一、 基础理论 各个数据模型都包含一些假设，当数据满足这些假设时，使用这些模型得到的结果才会更准确。比如广义线性模型要满足“线性”和“独立性”等条件。为了适应更多数据类型，开发出了各种模型，可根据数据情况，选择合适的模型。比如，如果数据不满足“线性”，则可考虑广义可加模型；如果不满足“独立性”，则可以考虑混合效应模型(mixed effect model)。
多水平模型同时包含多个分类因子数据，最主要特点就是非独立性，在多个水平上都存在残差，因此适合混合效应模型，总的来说，其思想就是把高水平上的差异估计出来，这就使得残差变小，估计的结果更为可靠。混合效应模型又称随机效应模型(Random Effect model)，分层线性模型，随机系数模型，方差成分模型等。
比如，一份包含不同施肥处理的多土层微生物数据，其中不同施肥处理与不同土壤深度即是嵌套数据(多水平数据)。
如果用线性模型分析不同施肥处理间微生物群落的差异，则没有考虑到不同土壤深度的微生物群落的差异，暗含了假设：不同土壤深度的微生物群落随不同施肥处理变化的截距与斜率都是相同的。不同土壤深度土壤的微生物群落差异就被线性模型归类到误差中去了。
如何解决这一问题呢？其中一种方法就是使用固定效应模型(Fixed Effect Model)，即将不同土壤深度的微生物群落结构随不同施肥处理变化的截距差异和斜率差异都估计出来。在土壤深度分类较少时可以这么做，将次级分类水平作为虚拟变量回归，3分类，则估计2个截距差异和斜率差异。当次级分类水平过多时，需要估计的参数太多，用虚拟变量就会消耗太多的自由度，估计结果不可靠，此时即可考虑使用混合效应模型。
固定效应与随机效应因子之间没有明显的分类，但显然随机效应因子要是分类数据，且数据跟随机效应存在相关性。有文章推荐随机效应的分类水平最好大于5类，因为当分类水平较少时，模型对方差的估计不太准确。当随机因子大于1个时，随机因子间的关系也需要注意，根据随机因子间关系，可能包括交叉(Crossed)、部分交叉或嵌套(nested)。
混合效应模型也分为线性混合效应模型、广义线性混合效应模型和非线性混合效应模型。此文章介绍使用R中lme4包进行线性混合效应模型分析。
线性混合效应模型假设：
1. 残差应该是正态分布的-可以适当放宽，前提是预测值与残差没有相关性，
2. 残差的方差是同质的-非常重要的假设；
3. 随机效应的观测是相互独立的；
4. 自变量与因变量存在线性关系；
5. 自变量间不存在相关性-方差膨胀因子筛选或者数据降维。
当然，对数据中异常点的检测也是很有必要的。
二、数据准备 此套数据是嵌套数据，包含分类因子depth和tillage。嵌套数据中包含多个分类自变量，数据是非独立性的，模型构建时考虑使用混合效应模型。选择pH为因变量。
​# 设置工作路径 #knitr::opts_knit$set(root.dir=&#34;D:\\EcoEvoPhylo\\MEM\\LMM&#34;)# 使用Rmarkdown进行程序运行 Sys.setlocale(&#39;LC_ALL&#39;,&#39;C&#39;) # Rmarkdown全局设置 #options(stringsAsFactors=F)# R中环境变量设置，防止字符型变量转换为因子 library(tidyverse) library(rstatix) library(car) library(lme4) library(lmerTest) # 模型固定效应系数检验 library(multilevelTools) # 模型诊断检验 library(extraoperators) library(JWileymisc) # 模型诊断及APAStyler以表格形式输出模型结果 library(effectsize) # 计算标准化回归系数 library(influence.">
  <meta property="og:locale" content="zh_CN">
  <meta property="og:type" content="article">
    <meta property="article:section" content="posts">
    <meta property="article:published_time" content="2024-02-15T15:45:46+08:00">
    <meta property="article:modified_time" content="2024-02-15T15:45:46+08:00">

	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link rel="dns-prefetch" href="//fonts.googleapis.com">
	<link rel="dns-prefetch" href="//fonts.gstatic.com">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700">

	<link rel="stylesheet" href="/css/style.css">
	

	<link rel="shortcut icon" href="/favicon.ico">
		
  


</head>
<body class="body">
	<div class="container container--outer">
		<header class="header">
	<div class="container header__container">
		
	<div class="logo">
		<a class="logo__link" href="/" title="编程大咖" rel="home">
			<div class="logo__item logo__text">
					<div class="logo__title">编程大咖</div>
					
				</div>
		</a>
	</div>
		<div class="divider"></div>
	</div>
</header>
		<div class="wrapper flex">
			<div class="primary">
			
<main class="main" role="main">
	<article class="post">
		<header class="post__header">
			<h1 class="post__title">R统计绘图-线性混合效应模型详解(理论、模型构建、检验、选择、方差分解及结果可视化)</h1>
			
		</header>
		<div id="gatop"></div>
		<div class="content post__content clearfix">
			
<div id="content_views" class="htmledit_views">
                    <p><strong>目录</strong></p> 
<p style="margin-left:40px;"><a href="#%E4%B8%80%E3%80%81%20%E5%9F%BA%E7%A1%80%E7%90%86%E8%AE%BA" rel="nofollow">一、 基础理论</a></p> 
<p style="margin-left:40px;"><a href="#%C2%A0%E4%BA%8C%E3%80%81%E6%95%B0%E6%8D%AE%E5%87%86%E5%A4%87" rel="nofollow">二、数据准备</a></p> 
<p style="margin-left:40px;"><a href="#%E4%B8%89%E3%80%81%E6%9E%84%E5%BB%BA%E7%BA%BF%E6%80%A7%E6%B7%B7%E5%90%88%E6%95%88%E5%BA%94%E6%A8%A1%E5%9E%8B%28LMMs%29" rel="nofollow">三、构建线性混合效应模型(LMMs)</a></p> 
<p style="margin-left:80px;"><a href="#3.1%20lme4%E7%BA%BF%E6%80%A7%E6%B7%B7%E5%90%88%E6%95%88%E5%BA%94%E6%A8%A1%E5%9E%8Bformula" rel="nofollow">3.1 lme4线性混合效应模型formula</a></p> 
<p style="margin-left:80px;"><a href="#3.2%20%E9%9A%8F%E6%9C%BA%E6%88%AA%E8%B7%9D%E6%A8%A1%E5%9E%8B%E6%9E%84%E5%BB%BA%E5%8F%8A%E6%A3%80%E9%AA%8C" rel="nofollow">3.2 随机截距模型构建及检验</a></p> 
<p style="margin-left:80px;"><a href="#3.3%20%E9%9A%8F%E6%9C%BA%E6%88%AA%E8%B7%9D%E6%A8%A1%E5%9E%8B%E5%88%86%E6%9E%90%E7%BB%93%E6%9E%9C%E8%A7%A3%E9%87%8A%E5%8F%8A%E5%8F%AF%E8%A7%86%E5%8C%96" rel="nofollow">3.3 随机截距模型分析结果解释及可视化</a></p> 
<p style="margin-left:80px;"><a href="#3.4%20%E9%9A%8F%E6%9C%BA%E6%96%9C%E7%8E%87%E6%A8%A1%E5%9E%8B%E6%9E%84%E5%BB%BA%E3%80%81%E6%A3%80%E9%AA%8C%E5%8F%8A%E5%8F%AF%E8%A7%86%E5%8C%96" rel="nofollow">3.4 随机斜率模型构建、检验及可视化</a></p> 
<p style="margin-left:40px;"><a href="#%E5%9B%9B%E3%80%81%E7%BA%BF%E6%80%A7%E6%B7%B7%E5%90%88%E6%95%88%E5%BA%94%E6%A8%A1%E5%9E%8B%E9%80%89%E6%8B%A9" rel="nofollow">四、线性混合效应模型选择</a></p> 
<p style="margin-left:80px;"><a href="#4.1%20%E5%A4%9A%E6%A8%A1%E5%9E%8B%E6%AF%94%E8%BE%83" rel="nofollow">4.1 多模型比较</a></p> 
<p style="margin-left:80px;"><a href="#4.2%C2%A0%E6%A8%A1%E5%9E%8B%E6%9C%80%E4%BC%98%E5%AD%90%E9%9B%86%E7%AD%9B%E9%80%89" rel="nofollow">4.2 模型最优子集筛选</a></p> 
<p></p> 
<h3 style="background-color:transparent;"><strong>一、 基础理论</strong></h3> 
<p>各个数据模型都包含一些假设，当数据满足这些假设时，使用这些模型得到的结果才会更准确。比如广义线性模型要满足“线性”和“独立性”等条件。为了适应更多数据类型，开发出了各种模型，可根据数据情况，选择合适的模型。比如，如果数据不满足“线性”，则可考虑广义可加模型；如果不满足“独立性”，则可以考虑混合效应模型(mixed effect model)。</p> 
<p>多水平模型同时包含多个分类因子数据，最主要特点就是非独立性，在多个水平上都存在残差，因此适合混合效应模型，总的来说，其思想就是把高水平上的差异估计出来，这就使得残差变小，估计的结果更为可靠。混合效应模型又称随机效应模型(Random Effect model)，分层线性模型，随机系数模型，方差成分模型等。</p> 
<p>比如，一份包含不同施肥处理的多土层微生物数据，其中不同施肥处理与不同土壤深度即是嵌套数据(多水平数据)。</p> 
<p>如果用线性模型分析不同施肥处理间微生物群落的差异，则没有考虑到不同土壤深度的微生物群落的差异，暗含了假设：不同土壤深度的微生物群落随不同施肥处理变化的截距与斜率都是相同的。不同土壤深度土壤的微生物群落差异就被线性模型归类到误差中去了。</p> 
<p>如何解决这一问题呢？其中一种方法就是使用固定效应模型(Fixed Effect Model)，即<strong>将不同土壤深度的微生物群落结构随不同施肥处理变化的截距差异和斜率差异都估计出来</strong>。在土壤深度分类较少时可以这么做，将次级分类水平作为虚拟变量回归，3分类，则估计2个截距差异和斜率差异。当次级分类水平过多时，需要估计的参数太多，用虚拟变量就会消耗太多的自由度，估计结果不可靠，此时即可考虑使用混合效应模型。</p> 
<p>固定效应与随机效应因子之间没有明显的分类，但显然随机效应因子要是分类数据，且数据跟随机效应存在相关性。有文章推荐<strong>随机效应的分类水平最好大于5类</strong>，因为当分类水平较少时，模型对方差的估计不太准确。当随机因子大于1个时，随机因子间的关系也需要注意，<strong>根据随机因子间关系，可能包括交叉(Crossed)、部分交叉或嵌套(nested)。</strong></p> 
<p>混合效应模型也分为线性混合效应模型、广义线性混合效应模型和非线性混合效应模型。此文章介绍使用R中lme4包进行线性混合效应模型分析。</p> 
<p></p> 
<p><strong>线性混合效应模型假设：</strong></p> 
<p><strong>1. 残差应该是正态分布的-可以适当放宽，前提是预测值与残差没有相关性，</strong></p> 
<p><strong>2. 残差的方差是同质的-非常重要的假设；</strong></p> 
<p><strong>3. 随机效应的观测是相互独立的；</strong></p> 
<p><strong>4. 自变量与因变量存在线性关系；</strong></p> 
<p><strong>5. 自变量间不存在相关性-方差膨胀因子筛选或者数据降维。</strong></p> 
<p><strong>当然，对数据中异常点的检测也是很有必要的。</strong></p> 
<p></p> 
<h3><strong> 二、数据准备</strong></h3> 
<p></p> 
<p>此套数据是嵌套数据，包含<strong>分类因子depth和tillage</strong>。嵌套数据中包含多个分类自变量，数据是非独立性的，模型构建时考虑使用混合效应模型。选择<strong>pH为因变量</strong>。</p> 
<pre><code>​# 设置工作路径
#knitr::opts_knit$set(root.dir="D:\\EcoEvoPhylo\\MEM\\LMM")# 使用Rmarkdown进行程序运行
Sys.setlocale('LC_ALL','C') # Rmarkdown全局设置
#options(stringsAsFactors=F)# R中环境变量设置，防止字符型变量转换为因子
library(tidyverse)
library(rstatix)
library(car)
library(lme4)
library(lmerTest) # 模型固定效应系数检验
library(multilevelTools) # 模型诊断检验
library(extraoperators)
library(JWileymisc) # 模型诊断及APAStyler以表格形式输出模型结果
library(effectsize) # 计算标准化回归系数
library(influence.ME) # 检测高影响观测点
library(GGally)
​
# 2.1 导入数据
env &lt;- read.csv("env.csv",row.names = 1)
env %&gt;% head
​
# 2.2 计算均值与标准误
env %&gt;%
  group_by(condition) %&gt;%
  get_summary_stats(names(env[4:ncol(env)]),type="mean_se") %&gt;%
  left_join(env[1:3],by = "condition") -&gt; data
data %&gt;% sample_n_by(tillage,size=2)</code></pre> 
<p></p> 
<p><img alt="c2046952b409086111d98e2338e5b308.png" src="https://images2.imgbox.com/ed/55/cbS3YjUG_o.png"></p> 
<p style="text-align:center;"><strong>图1</strong><strong>|原始数据表</strong><strong>，env.csv。</strong></p> 
<p></p> 
<p></p> 
<p><img alt="9a61fc1ff5c34cf6b30b5c1a4ec6a785.png" src="https://images2.imgbox.com/9b/a5/RFelRPpr_o.png"></p> 
<p style="text-align:center;"><strong>图2</strong><strong>|均值-标准误差计算结果</strong><strong>，data。</strong></p> 
<p></p> 
<pre><code># 2.3 数据探索-查看数据是否适合进行线性混合效应模型分析
## 2.3.1 ICC-组内相关系数计算
icc1 &lt;- iccMixed("pH","depth",env)
icc1
icc2 &lt;- iccMixed("pH","tillage",env)
icc2</code></pre> 
<p></p> 
<p><img alt="176293ac65a92c2738797d2118d9953e.png" src="https://images2.imgbox.com/ad/ba/c1ovvsFg_o.png"></p> 
<p style="text-align:center;"><strong>图3</strong><strong>|组内相关系数计算结果</strong><strong>，icc1。</strong>intra-class correlation coefficient (ICC)将变量差异分解为组内和组间差异，此处将depth作为随机截距，Sigma列依次为随机截距方差(组间差异)，残差(组内差异)。ICC=0表示差异全部来自组内个体差异，ICC=1表示变量差异全部来自组间，<strong>此处ICC=0.5062462表明depth水平间的方差挺大的，可以考虑使用混合效应模型</strong>。</p> 
<p></p> 
<pre><code>## 2.3.2 计算有效样本大小
nEffective(n = length(unique(env$depth)),
           k = nrow(env)/length(unique(env$depth)),
           dv = "pH",
           id = "depth",data=env
                  )</code></pre> 
<p></p> 
<p><img alt="06b89e5167a6389af5d84dc801f28f7b.png" src="https://images2.imgbox.com/2e/e2/pJOjy2Pe_o.png"></p> 
<p style="text-align:center;"><strong>图4</strong><strong>|effective sample size。</strong>对数据提供的有效独立样本数量的估计。N为独立的样本数量，k为每个独立样本的重复测量次数。</p> 
<p></p> 
<pre><code>## 2.3.3 因变量分布、极端值探索
### 将因变量按照分类因子进行均值分解
#### depth
tmp1 &lt;- meanDecompose(pH ~ depth, data = env)
tmp1
tmp1$`pH by depth`
tmp1$`pH by residual`
plot(testDistribution(tmp1[["pH by depth"]]$X,
                      extremevalues = "theoretical", ev.perc = .001),
     varlab = "Between Depth")
​
plot(testDistribution(tmp1[["pH by residual"]]$X,
                      extremevalues = "theoretical", ev.perc = .001),
     varlab = "Within Depth")#图中黑色点表示极端值。
​
#### tillage
tmp2 &lt;- meanDecompose(pH ~ tillage, data = env)
tmp2
do.call(cowplot::plot_grid, c(lapply(names(tmp2), function(x) {
  plot(JWileymisc::testDistribution(tmp2[[x]]$X), plot = FALSE, varlab = x)$Density
}), ncol = 1))</code></pre> 
<p></p> 
<p><img alt="859f2a8b2e376b481edfe1669a44fecc.png" src="https://images2.imgbox.com/6a/26/UFEM46EL_o.png"></p> 
<p style="text-align:center;"><strong><strong>图5</strong><strong>|均值分解图</strong><strong>，Within Depth。</strong></strong></p> 
<p></p> 
<pre><code>## 2.3.4 散点图可视化数据分布趋势
### width format转为long format
(env %&gt;%
  gather(key = "variable",value = "value",-condition,-tillage,-depth) %&gt;%
  rstatix::reorder_levels(variable,
                 order =c("pH","OM", "OC", 
                          "Ammonia", "Nitrate","AHN",  
                          "TN", "TP", "TK", 
                          "AP", "AK"
                           )) -&gt; data.p)
​
### 设置颜色
col1 &lt;- colorRampPalette(colors =c("#56B1F7","#132B43"),space="Lab") 
​
### 绘制分面-分组散点图
(data.p %&gt;%  ggplot2::ggplot(aes(
  x = factor(tillage,levels=c("CK","WL","NT","PT")),
  y = value,
  color= factor(depth,levels = unique(data.p$depth))))+
  geom_point(
    position = position_dodge(0.8), #调整site之间的宽度距离。
    width = 0.5,size = 1
  )+
  scale_color_manual(name = "Depth",
                     # values = ggsci::pal_d3("category10")(10),
                     values = col1(3),
                     breaks = c(unique( as.character(data.p$depth) )))+
  facet_wrap(.~variable,ncol = 4,scales = "free")+
  labs(x = NULL, y = NULL) -&gt; p1) # 绘图函数加上括号，赋值给变量的同时，会在屏幕上显示。
​
### 输出pdf图到本地
ggsave("p1.pdf", p1, device = "pdf",width = unit(10,"cm"),height = unit(8,"cm"))</code></pre> 
<pre> </pre> 
<p></p> 
<p><img alt="3d880977fc63f28a2e338e62514e770d.png" src="https://images2.imgbox.com/75/69/ZvOhDrcd_o.png"></p> 
<p style="text-align:center;"><strong><strong>图6</strong><strong>|long format格式数据表</strong><strong>，data.p。</strong></strong></p> 
<h3></h3> 
<p></p> 
<p><img alt="0fd50ec4552e592037e1a36255c3825c.png" src="https://images2.imgbox.com/27/4e/jjQrKobD_o.png"></p> 
<p style="text-align:center;"><strong><strong>图7</strong><strong>|可视化pH数据分布</strong><strong>，p1.pdf。</strong></strong></p> 
<p></p> 
<pre><code>## 2.3.5 绘制变量相关性图
### 设置绘图颜色
cols &lt;- ggsci::pal_jco()(7) 
### 绘制相关性图
my_density &lt;- function(data, mapping) {
 ggplot(data = data, mapping = mapping) +
 geom_density() 
} # 自定义函数
​
(
 ggpairs(env,columns = 4:14, 
 ggplot2::aes(color = tillage), # 按分组信息分别着色、计算相关性系数和拟合
 upper = list(continuous = "cor"), 
 lower = list(continuous = wrap("smooth",method = "lm",se = FALSE)), # se = FALSE,不展示置信区间 
 diag = list(continuous = my_density))+
 ggplot2::scale_color_manual(values = cols)+
 theme_bw() -&gt; p2
 )
​
### 输出pdf图到本地
pdf("p2.pdf",height = 20,width = 20,family = "Times")
print(p2)
dev.off()</code></pre> 
<p></p> 
<p><img alt="718ac398e780abae33453a0ab4d82c01.png" src="https://images2.imgbox.com/7f/20/TYEh4szm_o.png"></p> 
<p><strong><strong>图8</strong><strong>|变量相关性线性拟合图</strong><strong>，p2.pdf。</strong></strong>由图可知，很多两两变量的关系在tillage水平中的截距和斜率是不一致的。</p> 
<p></p> 
<h3><strong>三、构建线性混合效应模型(LMMs)</strong></h3> 
<p></p> 
<p>混合效应模型是指包含固定效应和随机效应的模型，固定效应部分就是线性模型模式，随机效应可以分为随机截距模型和随机斜率模型两大类。固定效应因子与随机效应因子没有很严格的区分，更多是根据自己的研究目的进行设置，最后模型都要满足线性混合模型的假设以及符合科学性。</p> 
<p></p> 
<p>此处使用<strong>lme4执行线性混合效应模型</strong>，(1+depth)表示depth是随机因子，截距随机。lme4包提供了进行线性混合效应模型、广义线性混合效应模型和非线性混合效应模型拟合和分析的功能。nlme包也可用于混合效应模型的建模。随机效应项在函数表达式中表现为(expr|factor)，expr是一个线性或广义线性等模型公式，factor是随机因子。<strong>lme4中用不同的formula区分交叉或嵌套数据</strong>。</p> 
<p>此过程是模型矩阵与分组因子的一种特殊交互，用以确保固定因子模型矩阵对于分组因子各水平都有不同的影响。分组因子效应被建模为未观察到的随机变量，而不是未知的固定参数。随机截距模型的截距的平均值和标准差是要估计的参数，模型将随机效应的任何非零均值合并为固定效应参数。<strong>函数默认执行限制性极大似然估计(REML)，REML假设固定效应结构是正确的,在比较具有不同固定效应的模型时，应该使用最大似然(ML)</strong>。因为ML不依赖于固定效应的系数。但ML对两个具有嵌套随机结构的模型进行比较时，对方差项的估计量存在偏差。因此，<strong>具有相同固定效应的模型，使用REML比较随机效应不同的模型</strong>。</p> 
<p>模型(固定效应系数和模型比较)显著性检验方法可选(效果从弱到强)：</p> 
<p>1）Wald Z-tests，固定效应系数显著性检验，适合大数据集；</p> 
<p>2）Wald t-tests (but LMMs need to be balanced and nested)；</p> 
<p>3）Likelihood ratio tests，只能用于ML拟合模型，可比较固定效应或随机效应不同的两个模型，那个能更好的拟合数据；</p> 
<p>4)  Kenward-Roger and Satterthwaite approximations for degrees of freedom，可比较两个固定效应模型的差异显著性;</p> 
<p>5）MCMC，不适合随机斜率模型;</p> 
<p>6）parametric bootstrap confidence intervals。</p> 
<p>当样本量足够时p值获取可以通过LRT或Wald t检验模型，但样本量较少时更推荐使用Kenward-Roger(只能用于REML)，Satterthwaite approximations(REML或ML)或parametric bootstrap。</p> 
<p></p> 
<h4><strong>3.1 lme4线性混合效应模型formula</strong></h4> 
<p></p> 
<p>随机截距模型：模型中只包含随机截距；随机斜率模型：模型中包含随机斜率。</p> 
<pre><code># 3.1.1 线性回归模型
fm0 &lt;- lm(pH ~ tillage + AP, 
           data = env)
fm0 %&gt;% summary
​
​
# 3.1.2 随机截距模型-depth的各水平都有对应的截距，模型会估计这些截距的均值和标准差。
control &lt;- lmerControl(
  optCtrl = list(
   algorithm = "NLOPT_LN_NELDERMEAD",
   xtol_abs = 1e-12,
   ftol_abs = 1e-12,
   check.conv.singular = .makeCC(action = "ignore", 
                                 tol = 1e-12)
  )
)
​
fm1 &lt;- lmer(pH ~ tillage + AP + (1|depth), 
           data = env,
           REML = FALSE,
           control = control)
fm1 %&gt;% summary
​
# 3.1.3 随机截距模型-添加先验prior截距均值
fm2 &lt;- lmer(pH ~ tillage + AP + offset(AP) + (1|depth), 
           data = env,
           REML = FALSE,
           control = control)
fm2 %&gt;% summary
​
​
# 3.1.4 混合效应模型：相关随机系数和截距模型
##lme4假设同一随机效应项的所有系数项是相关的。
fm3 &lt;- lmer(pH ~ tillage + AP + (1+tillage|depth), 
           data = env,
           REML = FALSE,
           control = control)
fm3 %&gt;% summary
​
​
# 3.1.5 指定不相关随机系数和截距模型-相当于(tillage||depth)
fm4 &lt;- lmer(pH ~ tillage + AP + (1|depth)+(0+tillage|depth), 
           data = env,
           REML = FALSE,
           control = control)
fm4 %&gt;% summary
​
​
# 3.1.6 考虑交互效应的随机截距模型-相当于(1|tillage) +(1|tillage:depth)。
##depth必须嵌套于tillage,不同tillage水平，depth间的pH不独立且具有差异。
fm5 &lt;- lmer(pH ~ AP + (1|tillage/depth),
           data = env,
           REML = FALSE,
           control = control)
fm5 %&gt;% summary
​
# 3.1.7 两组分类因子混合效应模型-如果同一样本在两个随机因子处都有观测， 则是交叉数据。
##将tillage与depth合并因子condition纳入分析，则是交叉数据。
##此处观察的是所有实验处理(tillage)和采样区域(condition)的对因变量的影响。
fm6 &lt;- lmer(pH ~ AP + (1|tillage) + (1|condition), 
           data = env,
           REML = FALSE,
           control = control) # 可以与fm6进行比较，观察两者差异。
fm6 %&gt;% summary
​
​
# 3.1.8 混合效应模型-depth各水平在tillage和AP都有不同斜率和不同截距。
fm7 &lt;- lmer(pH ~ AP + tillage + (tillage + AP|depth), 
           data = env,
           REML = FALSE,
           control = control)
fm7 %&gt;% summary
​
​
# 3.1.9 随机斜率模型
fm8 &lt;- lmer(pH ~ tillage + AP +(0 + tillage|depth), # 0表示固定截距。
           data = env,
           REML = FALSE,
           control = control)
fm8 %&gt;% summary
​</code></pre> 
<p>出现<strong>boundary (singular) fit: see help('isSingular')</strong>警告，要么修改随机效应，要么改用贝叶斯混合效应模型。</p> 
<p>模型构建都不是一蹴而就的,当自变量较多时，可以先构建全模型，模型检验不显著且不是研究关注核心的自变量，可以删除后，重构模型</p> 
<p></p> 
<h4><strong>3.2 随机截距模型构建及检验</strong></h4> 
<p></p> 
<p></p> 
<p><img alt="12ea5f88893968203c8a2ee45b3d1c69.png" src="https://images2.imgbox.com/76/9a/POru7aQV_o.png"></p> 
<pre><code># 3.2.1 构建随机截距模型
control &lt;- lmerControl(
  optCtrl = list(
   algorithm = "NLOPT_LN_NELDERMEAD",
   xtol_abs = 1e-12,
   ftol_abs = 1e-12,
   check.conv.singular = .makeCC(action = "ignore", 
                                 tol = 1e-12)
  )
)
##lmerTest::lmer()输出结果包含模型系数检验的p值，lme4::lmer()输出结果则不包含。
fm1 &lt;- lmerTest::lmer(pH ~ tillage + A + (1|depth), 
           data = env,
           REML = FALSE,
           control = control) 
​
# 3.2.2 模型诊断
## JWileymisc::modelDiagnostics()
fmd1 &lt;- modelDiagnostics(
  fm1,
  ev.perc = 0.001 # 可设置为0-1，表示理论分布的比例，超出该比例的值被视为极值。
  )
### 绘制残差诊断图
plot(fmd1,ask=FALSE,nrow=3)
​
### 提取极端值-如果有极端值，则可使用update()函数删除该数据点且更新模型。
fmd1$extremeValues # 此数据没有异常值，所以为null。</code></pre> 
<pre><code>​</code></pre> 
<p></p> 
<p><img alt="55d9b41de8c124934f644dea400f03e6.png" src="https://images2.imgbox.com/b3/bc/DZxYgyZl_o.png"></p> 
<p><strong>图9|随机截距模型检验图</strong><strong>。</strong>拟合模型之后，还要检验模型是否符合线性混合效应模型的假设。模型检验图的数量根据固定效应和随机效应数量变化。此模型的模型检验组合图中的第一幅图是残差的分布，应该要大致符合正态分布。第二幅图是残差-预测值图可以大致看出数据是否符合“同方差性”，残差值应该围绕0均匀分布，没有明显的分布趋势。最后，蓝色虚线表示预测值残差的第10%和第90%分位数（根据分位数回归模型估计），如果残差的方差是同质的，蓝色虚线应该是平坦且彼此平行的。如图所示，图中残差分布有明显的趋势，不太适合线性模型，可以改换非线性混合模型，或者残差异质性不严重，也可忽略。最后一幅图是depth随机截距的单变量分布。模型敏感性分析是一种评估模型结果对于参数变化或假设的变化的稳定性和影响的方法，模型假设检验就是敏感性分析的重要内容。</p> 
<p></p> 
<pre><code>## sjPlot包可以对模型假设检验结果进行可视化
fmd1.sj &lt;- sjPlot::plot_model(fm1, type = "diag")
# fmd1.sj[[1]] # 残差正态分布及离群值检验。
# fmd1.sj[[2]]$depth # 随机效应的Q-Q图。
# fmd1.sj[[3]] #残差正态分布检验。
# fmd1.sj[[4]]#残差方差同质性检验。
### 拼图并输出到本地
(fm1.assumptions &lt;- cowplot::plot_grid(fmd1.sj[[1]],fmd1.sj[[2]]$depth, fmd1.sj[[3]], fmd1.sj[[4]],
                   labels = c("A", "B","C","D")))
cowplot::save_plot(
  "fm1.assumptions.png",
  fm1.assumptions)
​
## performance::check_model()也可对模型假设检验结果进行可视化
theme_set(theme_classic(base_size = 6)) # windows太小，绘图会报错，先将ggplot2绘图的字体设置小一点。
pdf("check_model.pdf",width = unit(12,"cm"),height = unit(12,"cm"),family = "Times")
performance::check_model(fm1) 
dev.off()
​</code></pre> 
<p></p> 
<p><img alt="e8cfe9d9e1c043792e80145900fa9dfb.png" src="https://images2.imgbox.com/67/9b/aUk6J6qW_o.png"></p> 
<p><strong>图10|随机截距模型假设检验图，fm1.assumptions.png</strong><strong>。</strong>sjPlot::plot_model()可以对很多模型的假设检验和模型参数进行绘图，更多参数细节可以?plot_model查看函数帮助信息。R中进行相同统计分析的函数很多，使用函数可视化时，还是要知道函数使用的什么数据以及对数据进行过怎样的处理。</p> 
<p></p> 
<p></p> 
<p><img alt="6e89f7263f408f6baed59bf60fc0d372.png" src="https://images2.imgbox.com/d8/66/cthQRpH1_o.png"></p> 
<p><strong>图11|随机截距模型假设检验图，check_model.pdf</strong><strong>。</strong>performance::check_model()的模型检验结果更全，图也更美观。</p> 
<p></p> 
<pre><code>## 检验模型自变量是否具有共线性-一般阈值为5或10等
car::vif(fm1) # 此模型的两个自变量共线性不强。</code></pre> 
<p></p> 
<p><img alt="de9cc977feb19c17078dabce6c7a175f.png" src="https://images2.imgbox.com/db/a4/GsocnP8M_o.png"></p> 
<p><strong>图12|方差膨胀因子计算结果</strong><strong>。</strong>vif输出结果包括variance-inflation(VIF,模型所有项df =1),generalized variance-inflation factors (GVIF, df&gt;1)和自由度校正GVIF值。</p> 
<p></p> 
<pre><code>## 计算unadjusted ICC和adjusted ICC
performance::icc(fm1) # 有时也称为variance partition coefficient (VPC)。</code></pre> 
<pre><code>​</code></pre> 
<p></p> 
<p><img alt="59741006b38a572361fe34f240daf055.png" src="https://images2.imgbox.com/de/03/S3qHchz6_o.png"></p> 
<p><strong>图13|组内相关系数计算结果</strong><strong>。</strong>模型未校正ICC代表模型中只包含随机效应时的组内相关系数，adjusted ICC表示模型同时考虑随机效应和固定效应时，随机因子不同水平之间的相关性。ICC的取值范围在0到1之间，其值越小代表随机因子水平内的相似性并不比水平间的相似性高，表示没有必要将此因子设置为随机因子。</p> 
<p></p> 
<pre><code>## 模型高影响力观测点检测：influence.ME::dfbetas.estex()
##leave-one-out  diagnostics，重点观察改变模型系数超过其原值一半的观测点。
### 逐个删除观测点，计算数据改变后模型固定系数的变化。
alt.est &lt;- influence(fm1,obs=TRUE)
alt.est$or.fixed # 原模型固定因子系数
alt.est$alt.fixed # 去除某一观测点后，模型固定因子的系数
alt.est$or.se
alt.est$alt.se
​
### 计算数据改变后模型与全模型的固定系数的标准化差异：
##计算公式为：(原始模型参数-删除观测点后模型参数)/删除观测点后模型的标准误差。
##dfbeta的绝对值越大，删除该观测后的模型系数改变越大。cut-off值一般选2/sqrt(n),n表示检测的观测点的数量。此处为2/sqrt(36)。
##to.sort = 1表示按照截距变化值降序排列。
dfbetas.estex(alt.est,sort=TRUE,to.sort = 1 ) 
​
### 基于完整数据集的（混合效应）回归模型与删除了某些观测点的模型之间参数估计的百分比变化。以绝对值显示。
##R包文章中的计算公式为：(原模型参数-删除某一个观测后模型参数)/原模型参数*100%。
##pchange()实际计算公式为：(删除某一个观测后模型参数-原模型参数)/删除某一个观测后模型参数*100%。因此此函数计算有误，不需要参考。了解计算原理，可自行提取数据进行计算。
pchange(alt.est, parameters = 0, abs=TRUE) # 删除第8个样本后，tillagePT的参数估计变化较大。
​
### cook's距离计算-表示模型固定效应参数受观测点的影响程度。
##一般阈值设置为4/n,此处为4/36。
cooks.distance(alt.est)
​
### 删除某观测点前后固定效应系数显著性检验结果的变化
#alt.est2 &lt;- influence(fm1,group="depth") # 也可以直接检测随机效应的各分类水平删除后，固定效应系数是否发生变化。
influence.ME::sigtest(alt.est, test=1.96)$Intercept
sigtest(alt.est, test=1.96)$tillageNT
sigtest(alt.est, test=-1.96)$tillagePT
sigtest(alt.est, test=1.96)$tillageWL
sigtest(alt.est, test=1.96)$AP #四个固定效应系数的显著性都未发生变化。
​</code></pre> 
<p></p> 
<p><img alt="e03dbf89501df33bee8adc9dbe9d7f8e.png" src="https://images2.imgbox.com/fc/6b/myS8FEua_o.png"></p> 
<p><strong><strong>图14|随机截距模型检验图</strong><strong>。</strong></strong>第8个观测点删除后，tillagePT系数变化过大，可使用sigtest进行检验删除该观测点之后，固定效应参数的显著性是否发生变化，看是否需要删除该观测点。</p> 
<p></p> 
<p></p> 
<p><img alt="20b3ecae754b838ca0cc7c3a44df58c6.png" src="https://images2.imgbox.com/a9/a0/bWrtDMQZ_o.png"></p> 
<p><strong><strong><strong>图15|删除某观测点后模型截距参数显著性的变化</strong><strong>。</strong></strong></strong>列内容依次代表删除某一观测之后，模型截距参数值(Altered.Teststat)、参数检验显著性(Altered.Sig)以及删除前后截距参数检验结果是否发生变化(Changed.Sig)。Altered.Sig的结果会随着函数中test值的正负而发生改变，Changed.Sig不会。输出结果中只需要看Changed.Sig列即可。<strong>因此使用R包，一定要知道他的计算原理，不能完全相信输出结果。</strong></p> 
<p></p> 
<pre><code>### 绘制观测点模型影响力图
plot(alt.est, which="dfbetas")
plot(alt.est, which="cook", 
     sort=TRUE,cutoff = 4/36,
     xlab="Cook´s Distance",
     ylab="Samples")
plot(alt.est, which="pchange")
plot(alt.est, which="sigtest")
​
### 删除第8观测点，更新模型及重新诊断模型-此处没有需要删除的观测点，此步只是展示如何更新模型。
fm1.2 &lt;-  update(fm1, data = env[-8,])
fmd1.2 &lt;- modelDiagnostics(fm1.2, ev.perc = .001)
plot(fmd1.2, ask = FALSE, nrow = 3)
fmd1.2$extremeValues
​</code></pre> 
<pre> </pre> 
<p></p> 
<p><img alt="2200df15ec0c5c9972f95b9304742354.png" src="https://images2.imgbox.com/a5/73/P7wkgr6W_o.png"></p> 
<p><strong>图16|cook's距离图</strong><strong>。</strong>某一观测点对模型参数的影响力，红色三角形表示超过设置阈值的观测点。influence.ME包中函数的计算公式和更多输出结果意义，请查看https://journal.r-project.org/archive/2012-2/RJournal_2012-2_Nieuwenhuis~et~al.pdf。<strong>个人更推荐使用car包检测模型的高影响力点。</strong></p> 
<p></p> 
<pre><code>## 推荐使用car包检测模型的高影响力点
car::influencePlot(fm1)</code></pre> 
<pre><code>​</code></pre> 
<p></p> 
<p><img alt="1bee5908b2d4d3c12e68928144ad1184.png" src="https://images2.imgbox.com/bd/83/q6r7cgJe_o.png"></p> 
<p><strong>图17|car::influencePlot()输出的高影响观测值</strong><strong>。</strong>推荐使用car包检测模型假设。更多线性模型假设检验信息，可参考<a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247486281&amp;idx=1&amp;sn=76e86ea6f1b43c4b0eb8522c20485900&amp;chksm=e89fda6ddfe8537bb055069539de960febe0f2dc9adc72358a38ca5931bb5c7dda98f4a4dea0&amp;scene=21#wechat_redirect" rel="nofollow" title="R统计绘图-多重线性回归(最优子集法特征筛选，leaps)">R统计绘图-多重线性回归(最优子集法特征筛选，leaps)</a>。</p> 
<p></p> 
<p></p> 
<p><img alt="a393fc958da94bc9ba0a31957b7169d8.png" src="https://images2.imgbox.com/38/8d/DDiXhpwo_o.png"></p> 
<p><strong>图18|car::influencePlot()输出的离群点、高杠杆值和强影响点的信息整合图</strong><strong>。</strong>图中纵坐标超过+2或小于-2的观测点可被认为是离群点，横坐标超过0.2或0.3的观测点有高杠杆值(通常为预测值的组合)。圆圈大小与影响成比例，圆圈很大的点可能是对模型参数的估计造成的不成比例影响的强影响点。没有通过检验的点将会在图后列出。</p> 
<p></p> 
<pre><code># 3.2.3 模型检验
##lmer()没有直接提供整体模型检验结果，可使用其它函数计算。
##multilevelTools包的modelTest()、lmerTest包的ranova()和JWileymisc包modelPerformance()能提供更多用于出版的检验信息，如果固定效应的边际R方等
## summary()-模型系数t检验-Satterthwaite's degrees of freedom method
fm1.res &lt;- fm1 %&gt;% summary
fm1.res
​
#vcov(fm1) %&gt;% cov2cor() # 固定系数的相关矩阵。
​
## 计算固定效应方差及随机效应解释方差的比例：总方差=固定效应方差+随机效应方差+残差。
(fix.var &lt;- var(model.matrix(fm1)%*%fixef(fm1))) # 固定效应方差：参考
0.002452/(fix.var+0.002452+0.017687)*100 # 1.686511%</code></pre> 
<pre><code>​</code></pre> 
<p></p> 
<p><img alt="8611ae35ba818a3160926ece6ecf065e.png" src="https://images2.imgbox.com/9b/7b/LKou2I62_o.png"></p> 
<p><strong>图19|fm1.res结果解释</strong><strong>。</strong>summary结果中包含AIC、BIC、LRT等模型评估值，可用于对使用相同算法(ML或REML)的模型间的比较。输出结果中还包括随机效应方差和残差，固定效应系数(截距+斜率)统计量及t检验结果以及固定效应相关性矩阵。模型的截距是5.831183,是depth三个水平截距的均值。Fixed effects中4个斜率的绝对值都大于对应误差，表明固定效应能与0区分开，系数可用。Fixed effects中tillageNT的斜率0.353252表示模型估计从CK到NT，pH的含量预测增加0.353252。tillagePT的系数0.082041的意义也是一样，从CK到PT，pH预计增加0.082041。模型中tillageCK是作为哑变量，模型系数为0，如果没有设置因子水平，函数则会根据字母顺序选择某个分类变量水平作为哑变量。AP的系数-0.023922表示AP每增加一个单位，pH降低0.023922。总方差=固定效应方差+随机效应方差+残差。depth的随机效应方差表示depth对土壤pH的影响，模型已给出0.002452，残差也已给出0.017687，固定效应的方差需要自己计算一下，可按照张霜老师的推文进行计算(https://blog.sciencenet.cn/home.php?mod=space&amp;uid=3442043&amp;do=blog&amp;id=1326172),值为 0.1252499。最后计算出depth能解释pH的1.686511%的方差[0.002452/(0.002452+0.017687+ 0.1252499)*100]。Correlation of Fixed Effects中输出了模型固定系数的相关矩阵，固定系数的Std.Error是估计方差的平方根。vcov(fm1)可以查看固定系数的估计方差,vcov(fm1) %&gt;% cov2cor()即是固定系数的相关矩阵。具体意义可查看：https://library.virginia.edu/data/articles/correlation-of-fixed-effects-in-lme4。</p> 
<p></p> 
<p>summary()没有对随机效应的方差和整体模型进行检测，接下来介绍随机效应和模型检验的结果。anova()函数可以通过LRT检验进行不同模型的比较。pbkrtest包提供函数可进行只针对REML模型的Kenward-Roger法检验。car::Anova()也可对线性混合效应模型进行检测，且方差分析方法和参数设置更多。</p> 
<pre><code>## 模型固定效应F检验
### Type III anova table with p-values for F-tests based on Satterthwaite's.
anova(fm1)#与anova(fm1,type = "marginal")结果相同。
​
​
### 基于Kenward-Roger法的模型检验只针对REML
fm1.1 &lt;- lmer(pH ~ AP + tillage + (1|depth),
            data = env,
            REML = TRUE,
            control = control)
if(requireNamespace("pbkrtest", quietly = TRUE))
anova(fm1.1, type=2, ddf="Kenward-Roger")
​
​
### Anova中的方差分析方法和参数设置更多-Analysis of Deviance Table (Type II Wald chisquare tests)
car::Anova(fm1)</code></pre> 
<pre><code>​</code></pre> 
<p></p> 
<p><img alt="791360e1712cd28ae04b28a6e00114b7.png" src="https://images2.imgbox.com/c3/6e/a7OM0Gyv_o.png"></p> 
<p><strong>图20|模型的Satterthwaite's检验结果</strong><strong>。</strong>anova函数中只有一个模型时，则会输出模型固定因子的F检验结果，结果显示三个固定因子的方差检验结果都存在统计学意义。</p> 
<p></p> 
<p></p> 
<p><img alt="b097f2e4aca44061a3d7761299ae5d98.png" src="https://images2.imgbox.com/15/fc/pw3IhAxn_o.png"></p> 
<p><strong>图21|模型的<strong>Kenward-Roger法</strong>检验结果</strong><strong>。</strong>Kenward-Roger法只能用于REML模型，当样本量较小时，更推荐使用此方法。</p> 
<p></p> 
<p></p> 
<p><img alt="b194e868cf44e3a793093feb95a166a8.png" src="https://images2.imgbox.com/15/70/15NyrvVn_o.png"></p> 
<p><strong>图22|模型的Wald chisquare法检验结果</strong><strong>。</strong>默认检验方法与anova()不同。更多检验方法可以查看：http://link.springer.com/article/10.3758%2Fs13428-016-0809-y。</p> 
<p></p> 
<pre><code>## ranova()-模型随机效应LRT检验
ranova(fm1)</code></pre> 
<pre><code>​</code></pre> 
<p></p> 
<p><img alt="d590bc3775c7f7e6358bc2b4f71ea603.png" src="https://images2.imgbox.com/b4/90/x620oegT_o.png"></p> 
<p><strong>图23|模型随机效应检验结果</strong><strong>。</strong>ranova()对模型随机效应的似然比检验(LRT)结果支持(1 | depth)的方差不显著不为0，则表示depth间无差异，这与depth对模型较低的方差解释率是对应的，则可以把考虑去除模型中的depth的随机截距。如果方差显著不为零，此随机效应则应该保留。</p> 
<p></p> 
<p>JWileymisc、modelsummary、export和sjPlot等包可以对模型进行检验、提取模型结果以及以文字、表格或图形展示出版需要统计信息：统计值、置信区间、p值等。</p> 
<pre><code>## modelTest()可以对模型进行检验并以表格形式提取出版需要统计信息：统计值、置信区间、p值等
fm1.da &lt;- JWileymisc::modelTest(fm1)
fm1.da$FixedEffects # 固定效应检验
fm1.da$RandomEffects # 随机效应检验
fm1.da$EffectSizes # 固定效应统计值，包括marginal R2、conditional R2、cohen’s F2和卡方检验结果。
fm1.da$OverallModel$Performance # 整体模型检验，包括AIC、BIC、MarginalR2和ConditionalR2等值。
​
# names(modelTest(fm1)) # 输出结果中包含的列表名。
# APAStyler(modelTest(fm1)) # 可用于去除极端值前后的模型结果比较:APAStyler(list(Original = mt, `Outliers Removed` = mt3))。
APAStyler(modelTest(fm1),
          format = list(
            FixedEffects = "%s, %s (%s; %s)",
            RandomEffects = c("%s", "%s (%s, %s)"),
            EffectSizes = "%s, %s; %s"),
          digits = 3,
          pcontrol = list(digits = 3, stars = FALSE,
                          includeP = TRUE, includeSign = TRUE,
                          dropLeadingZero = TRUE))</code></pre> 
<pre><code>​</code></pre> 
<p></p> 
<p><img alt="c96c3d3cf8d8d30d5315b24922a5b229.png" src="https://images2.imgbox.com/cb/b8/aGgcDrwd_o.png"></p> 
<p><strong>图24|模型综合检验结果，modelTest</strong><strong>。</strong>数据结果包括AIC/BIC等模型评估指标，随机效应方差和模型残差，固定效应统计量等。输出结果缩写代表的含义，可通过??modelTest查看函数的帮助文件。AIC (Akaike Information Criterion)；BIC (Bayesian Information Criterion)；LL (Log Likelihood)；LLDF (degrees of freedom for log likelihood)；Sigma (residual standard deviation)；R2 (R2 variance accounted for in the sample)；F2 (Cohen’s f2  effect size, calculated as [R2/(1−R2)])；AdjR2 (Sample size adjusted R2, a better estimate of population variance accounted for)；F (model F test)；FNumDF (numerator degrees of freedom for model F test)；FDenDF (denominator degrees of freedom for model F test)；P (p value for model F test)。</p> 
<p></p> 
<pre><code>## tab_model()以html形式输出模型参数检验结果。
(sjPlot::tab_model(fm1,
                  collapse.ci = TRUE,
                  p.style = "numeric_stars",
                  file="fm1.html")) # 以html表格形式输出模型参数，，使用的是Nakagawa's R2。</code></pre> 
<p></p> 
<p><img alt="0b7788c5c2e03bc9deca940a04c4cb55.png" src="https://images2.imgbox.com/1b/5f/SC6XMClo_o.png"></p> 
<p><strong>图25|模型参数检验结果，fm1.html</strong><strong>。</strong>数据结果包括AIC/BIC等模型评估指标，随机效应方差和模型残差，固定效应统计量和Marginal R2/Conditional R2等。不同函数的主要差异在于R2的计算方法，其他参数只是小数点位数设置差异。sjPlot::tab_model()使用performance::r2()为混合效应模型计算Nakagawa's R2。</p> 
<p></p> 
<pre><code>## modelsummary()-能直接将模型参数表格输出为word文档,可以方便的进行多个模型的参数提取及比较，还可以并行提取。
(modelsummary::modelsummary(list("fm1" = fm1),
                            stars=TRUE,
                            estimate = "{estimate} ({std.error}){stars}", # 展示模型固定效应统计量、标准误和显著性标记。
                            statistic = "conf.int",# 展示置信区间。
                            output = "fm1.docx")) # 使用的performance::r2()计算的R2,会与其他函数的提取的Marginal R2 / Conditional R2值不一样。</code></pre> 
<p></p> 
<p><img alt="28ce7862b51f77c2f3f700fae3e9923c.png" src="https://images2.imgbox.com/a5/a4/WIyeKFg3_o.png"></p> 
<p><strong>图26|模型参数检验结果，fm1.docx</strong><strong>。</strong>数据结果包括AIC/BIC等模型评估指标，随机效应方差和模型残差，固定效应统计量和边际效应等。modelsummary()使用performance::r2()为混合效应模型计算Nakagawa's R2,会与其他函数的提取的Marginal R2 / Conditional R2值有些微差别。其他参数只是小数点位数设置差异。</p> 
<p></p> 
<h4><strong>3.3 随机截距模型分析结果解释及可视化</strong></h4> 
<p></p> 
<pre><code># 3.3.1 模型系数解释
coef(fm1) # 未标准化模型系数。
effectsize(fm1) # 标准化回归系数，不是很有必要，实际预测时使用的是未标准化回归系数。
fixef(fm1) # 提取未标准化固定效应系数。
ranef(fm1) # 提取随机效应系数。</code></pre> 
<p></p> 
<p><img alt="e1fe89eba7b1a70688f4164a5dc4df7e.png" src="https://images2.imgbox.com/4b/c8/lmLYjE6V_o.png"></p> 
<p><strong>图27|未标准化模型系数，coef(fm1)</strong><strong>。</strong>提取系数可以看到，随机截距模型中，随机效应depth有三个不同的截距系数，各水平对应的其它自变量的斜率系数都是一样的。系数具体含义已在fm1.res中提过，这里不再赘述。</p> 
<p></p> 
<p></p> 
<p><img alt="454d2b340c94c1ee5084b77fe5d6f7a5.png" src="https://images2.imgbox.com/a4/82/GtNkl0Jb_o.png"></p> 
<p><strong>图28|标准化固定因子模型系数，effectsize(fm1)</strong><strong>。</strong>对自变量和因变量同时经过标准化处理后消除了量纲、数量级等差异的影响，然后构建模型得到的就是标准化回归系数，因此，标准化回归系数可以直观比较不同自变量对因变量的作用大小，但不一定具有统计学意义。未标准化回归系数的意义则是，在其它自变量保持不变的情况下，该自变量变化一个单位导致的因变量的变化量。当自变量中存在分类变量时，使用标准化回归系数那一解释系数意义，且在实际预测时，模型使用的是未标准化系数，因此标准化回归系数可用可不用。</p> 
<p></p> 
<pre><code># 3.3.2  Estimated marginal means (Least-squares means)-在其它因素保持不变的情况下的固定因子水平的均值。
emmeans::emmeans(fm1, ~tillage) # tillage各水平的pH最小二乘均值。
emmeans::emmeans(fm1, ~AP)
emmeans::emmeans(fm1, ~AP|tillage) # 两者交互
# env %&gt;% group_by(`tillage`) %&gt;% select(pH) %&gt;% rstatix::get_summary_stats() %&gt;% data.frame()</code></pre> 
<pre><code>​</code></pre> 
<p></p> 
<p><img alt="18149e02d5dd22d49ab4facbf3fdcc34.png" src="https://images2.imgbox.com/27/ed/gihGFe8d_o.png"></p> 
<p><strong>图29|估计边际均值结果，emmeans(fm1, ~tillage)</strong><strong>。</strong>估计边际均值结果中的emmean列表示固定因子变量各水平以及固定定量变量的pH的最小二乘均值，tillage的结果中WL的emmean值最大，表示pH在NT和WL的值更大，pH均值在两者中也是更大的，只有些微差别。结果解释可参考：https://www.zhihu.com/question/370213292。</p> 
<p></p> 
<pre><code># 3.3.3  Post-hoc / Contrast Analysis
library(knitr)
## tillage水平间估计边际均值的两两比较
emmeans::emmeans(fm1, pairwise ~ tillage, adjust = "bonferroni")$contrasts %&gt;% 
  tidy() %&gt;% 
  mutate_if(is.numeric, ~round(., 4)) %&gt;% 
  kable()
​
## tillage与AP交互效应的估计边际均值的两两比较
emmeans::emmeans(fm1, pairwise ~ tillage * AP, adjust = "bonferroni")$contrasts %&gt;% 
  tidy() %&gt;% 
  mutate_if(is.numeric, ~round(., 4)) 
​
## 估计边际均值事后检验结果绘图
emmeans::pwpp(emmeans::emmeans(fm1, pairwise ~ tillage * AP, adjust = "bonferroni"), type = "response")+theme_minimal()</code></pre> 
<pre><code>​</code></pre> 
<p></p> 
<p><img alt="7d514e3afe2b7d717e82da619f7a4b46.png" src="https://images2.imgbox.com/37/c0/6Lb7Qtmd_o.png"></p> 
<p><strong>图30|tillage水平间估计边际均值的两两比较</strong><strong>。</strong></p> 
<p></p> 
<p></p> 
<p><img alt="08c886c5a2759eedc1689f65f9323cc7.png" src="https://images2.imgbox.com/d9/8f/9M7Lg7oC_o.png"></p> 
<p><strong>图31|tillage水平间估计边际均值的两两比较</strong><strong>。</strong></p> 
<p></p> 
<p></p> 
<p><img alt="4a47ba59fe4f1f1ce3e0c69f9158cfa8.png" src="https://images2.imgbox.com/c5/d4/mjpDtHuG_o.png"></p> 
<p><strong>图32|估计边际均值事后检验结果绘图</strong><strong>。</strong></p> 
<p></p> 
<pre><code># 3.3.4 方差分解-不同方法计算出的R2结果会有差异，但是趋势都是一致的。
## 方法一：R2计算模型整体的MarginalR2和ConditionalR2 
R2(fm1)
​
## 方法二：modelTest()会计算模型整体和固定效应的MarginalR2和ConditionalR2。
fm1.da &lt;- JWileymisc::modelTest(fm1)
### 模型整体的MarginalR2和ConditionalR2，与R2()计算结果一致。
fm1.da$OverallModel$Performance %&gt;%
  select(Model,MarginalR2,ConditionalR2)
### 固定效应的MarginalR2和ConditionalR2。
fm1.da$EffectSizes %&gt;%
  select(Variable,MarginalR2,ConditionalR2)
​
## 方法三：r2()会计算模型整体的Nakagawa's MarginalR2和ConditionalR2。
performance::r2(fm1,version=TRUE)
​
## 方法四：MuMln包的r.squaredGLMM()只提供模型整体的marginal R2和conditional R2。
# install.packages("D://software//MuMIn_1.47.8.zip",'repos = NULL')
MuMIn::r.squaredGLMM(fm1) #计算模型的边际及条件R方,程辑包‘MuMIn’需要&gt;= 4.2.0。
​
## 方差分解：glmm.hp包的glmm.hp():"hierarchical partitioning"
glmm.hp::glmm.hp(fm1)$hierarchical.partitioning
​
## 方差分解结果绘图
### 方差分解绘图数据提取
r2 &lt;- round(glmm.hp::glmm.hp(fm1)$r.squaredGLMM,4)
fix.r2 &lt;- glmm.hp::glmm.hp(fm1)$hierarchical.partitioning
(plot_data &lt;- data.frame(
  variable = c("tillage","AP","depth","Unexplained"),
  explain = c(
    fix.r2[,3],
    r2[2]-r2[1],
    1-r2[2])*100, #用百分数显示。
  p.value = c(
    anova(fm1,type = "marginal")[,6],
    ranova(fm1)[2,6],
    1),
  response = "pH"
))
​
### 方差分解结果绘图
(plot_data %&gt;% 
  ggplot2::ggplot(
    aes(y=response,x=explain,fill=reorder(variable,-explain)))+
  geom_bar(position = "stack",
           stat = "identity",
           width=0.4)+
  geom_text(aes(label = ifelse(p.value &gt;0.05,"","*")),size=2.5)+
  ggthemes::theme_base()+
  labs(y="",x="Variation (%)")+
  scale_fill_brewer(type = "qual",palette = "Set2",
                    breaks= c("AP","tillage","depth","Unexplained"), #自定义图例顺序
                    guide = guide_legend(title = "", byrow = TRUE,nrow=1 )
                              )+
  scale_x_continuous(expand = c(0,0),
                     limits = c(0,100),
                     breaks = seq(0,100,25),
                     labels = seq(0,100,25))+
  theme(axis.ticks.y = element_blank(),
        plot.background = element_blank(),
        panel.grid = element_blank(),
        legend.position = "top",
        plot.margin=unit(c(2,1,0.25,1),'cm'),
        legend.background = element_rect(color=NULL)) -&gt; var.decom)
ggsave("var.decom.pdf",var.decom,device = "pdf",family="Times",width = 7,height = 3)</code></pre> 
<pre><code>​</code></pre> 
<p></p> 
<p><img alt="4a7af5214b2deda57e5faa062d1bbaae.png" src="https://images2.imgbox.com/68/3e/nJQH8OSA_o.png"></p> 
<p><strong><strong>图33|方差分解结果表</strong><strong>。</strong></strong>此处选择的glmm.hp包的glmm.hp()方差分解的结果。hierarchical partitioning法的方差分解结果，Unique表示固定因子的解释的方差，与fm1.da$EffectSizes中计算的固定效应的边际R2值相近。Average.share表示层次分割计算的共享方差，Individual表示固定因子的单独MarginalR2，I.perc(%)是固定因子独自解释因变量的方差占模型MarginalR2的比例。r.squaredGLMM的方差与R2的计算结果有些微差异，但是趋势是一致的。方差分解有很多算法，选用方法的时候应该弄清楚背后的原理，理论文章是要引用的。</p> 
<p></p> 
<p></p> 
<p><img alt="d4716dbc0a93b623fcaf0c61a57bcb22.png" src="https://images2.imgbox.com/22/01/j6MAZETg_o.png"></p> 
<p><strong><strong>图34|方差分解结果绘图</strong><strong>。</strong></strong>柱子中的星号表示固定效应参数检验显著。</p> 
<p></p> 
<pre><code># 3.3.5 绘制效应图(effect plot)
## 绘制随机效应水平间变化：绘制随机截距和斜率与模型总体截距和斜率的差异。
lattice::dotplot(ranef(fm1, condVar=T))
​
## 绘制固定效应预测效应图。
plot(effects::allEffects(fm1)) 
​
## 绘制模型预测效果图。
performance::check_predictions(fm1)</code></pre> 
<pre><code>​</code></pre> 
<p></p> 
<p><img alt="530a67a1fdbe628351cedc6d6f57c1d7.png" src="https://images2.imgbox.com/95/4d/qpAJuRzv_o.png"></p> 
<p><strong><strong>图35|</strong>随机效应系数散点图。</strong>随机截距模型只有截距的随机效应参数。</p> 
<p></p> 
<p></p> 
<p><img alt="ac6e6efcaa4c8027f73b12389caf09dc.png" src="https://images2.imgbox.com/ab/d5/4Pc3jtVP_o.png"></p> 
<p><strong><strong>图36|</strong>模型固定效应预测效应图。</strong>AP效应图横轴上的小竖线表示数据点。</p> 
<p></p> 
<p></p> 
<p><img alt="9b47b314b6503596cc1fb8213c1676b3.png" src="https://images2.imgbox.com/b3/45/Usj7tuKZ_o.png"></p> 
<p><strong><strong>图37|</strong>模型预测效果图。</strong></p> 
<p></p> 
<pre><code># 3.3.6 输出模型文字描述
report::report(fm1)</code></pre> 
<pre><code>​</code></pre> 
<pre> </pre> 
<p>We fitted a linear mixed model (estimated using ML and nloptwrap optimizer) to predict pH with tillage and AP (formula: pH ~ tillage + AP). The model included depth as random effect (formula: ~1 | depth). The model's total explanatory power is substantial (conditional R2 =<br> 0.88) and the part related to the fixed effects alone (marginal R2) is of 0.86. The model's intercept, corresponding to tillage = CK and AP = 0, is at 5.83 (95% CI [5.65, 6.01], t(29) = 67.05, p &lt; .001). Within this model:<br><br> - The effect of tillage [NT] is statistically significant and positive (beta = 0.35, 95% CI [0.22, 0.49], t(29) = 5.42, p &lt; .001; Std. beta = 0.88, 95% CI [0.55, 1.21])<br> - The effect of tillage [PT] is statistically non-significant and positive (beta = 0.08, 95% CI [-0.05, 0.22], t(29) = 1.25, p = 0.223; Std. beta = 0.20, 95% CI [-0.13, 0.54])<br> - The effect of tillage [WL] is statistically significant and positive (beta = 0.38, 95% CI [0.25, 0.51], t(29) = 6.04, p &lt; .001; Std. beta = 0.94, 95% CI [0.62, 1.26])<br> - The effect of AP is statistically significant and negative (beta = -0.02, 95% CI [-0.03, -0.02], t(29) = -10.61, p &lt; .001; Std. beta = -0.76, 95% CI [-0.91, -0.61])<br><br> Standardized parameters were obtained by fitting the model on a standardized version of the dataset. 95% Confidence Intervals (CIs) and p-values were computed using a Wald t-distribution approximation.</p> 
<pre>可参照此输出描述自己的结果。</pre> 
<pre> </pre> 
<h4><strong>3.4 随机斜率模型构建、检验及可视化</strong></h4> 
<p></p> 
<p><img alt="902ea33aec4fea7766fac55eb40ac13e.png" src="https://images2.imgbox.com/bf/f3/851xIKr9_o.png"></p> 
<p></p> 
<p>在文章中需要描述以下信息：1)模型描述(因变量、固定效应和随机效应)；2)数据是否满足线性混合模型假设；3)数据是否存在异常值及如何处理异常值；4)模型系数与模型检验结果；5)根据研究目的，有些还需要自变量的MarginalR2分解结果。</p> 
<p>理论知识在随机截距模型部分已提及，此处用随机斜率模型演示如何快速得到上述结果。</p> 
<p></p> 
<p>此处因为fm1使用的ML法，为了方便后续比较，后续模型都使用的ML法，但是ML法可能会低估随机效应的方差，所以<strong>模型构建可优先选用REML法</strong>。特别当混合效应模型存在嵌套随机效应时，则不应该选用ML算法。</p> 
<pre><code># 3.4.1 构建随机斜率模型
control &lt;- lmerControl(
  optCtrl = list(
   algorithm = "NLOPT_LN_NELDERMEAD",
   xtol_abs = 1e-12,
   ftol_abs = 1e-12,
   check.conv.singular = .makeCC(action = "ignore", 
                                 tol = 1e-12)
  )
)
fm3 &lt;- lmerTest::lmer(pH ~ tillage + AP + (1+tillage|depth), 
           data = env,
           REML = FALSE)
fm3.res &lt;- fm3 %&gt;% summary
fm3.res # 不是所有回归系数都显著。</code></pre> 
<pre><code>​</code></pre> 
<p></p> 
<p><img alt="ac13f24509c6b55ed4c38fd2570ce307.png" src="https://images2.imgbox.com/b3/86/2FuOkDIk_o.png"></p> 
<p><strong><strong>图38|</strong>随机斜率模型参数。</strong>随机斜率模型设置depth中pH的变化速度在tillage各水平不同，因此随机效应增加了三个随机斜率，tillageCK是对照组。结果中给出了随机斜率与随机截距的相关性，比较两者有比较高的相关性，一般比较好，但是如果非常接近1或−1就表示模型拟合有问题。</p> 
<p></p> 
<pre><code># 3.4.2 模型诊断-检验模型是否符合混合效应模型的假设及是否存在异常值。
theme_set(theme_classic(base_size = 6)) # windows太小，绘图会报错，先将ggplot2绘图的字体设置小一点。
pdf("fm3.check.model.pdf",width = unit(12,"cm"),height = unit(12,"cm"),family="Times")
(fmd3 &lt;- performance::check_model(fm3))
dev.off()
​
fmd3$INFLUENTIAL #查看是否存在异常点。</code></pre> 
<pre><code>​</code></pre> 
<p></p> 
<p><img alt="d2b84d854befce497732b775a4fe15c5.png" src="https://images2.imgbox.com/04/73/dpYrzfAB_o.png"></p> 
<p><strong>图39|随机斜率模型假设检验综合图</strong><strong>。</strong>混合线性效应模型需要满足的假设，在图中标题处有注明。与随机截距模型不同的时，此处随机斜率模型增加了三个随机斜率。</p> 
<p></p> 
<pre><code># 3.4.3 模型检验
## 固定效应显著性检验-图表中有关Marginal R2/Conditional R2的计算，推荐替换为MuMIn::r.squaredGLMM()的计算结果。
### 随机效应输出的是标准误
options(modelsummary_get = "all")
(modelsummary::modelsummary(list("fm3" = fm3),
                            stars=TRUE,
                            estimate = "{estimate} ({std.error}){stars}", # 展示模型固定效应统计量、标准误和显著性标记。
                            statistic = "conf.int",# 展示置信区间。
                            output = "fm3.docx")) 
### 随机效应输出的 Variance，两个函数的输出可以综合起来，选择自己需要的。
(sjPlot::tab_model(fm3,
                  collapse.ci = TRUE,
                  p.style = "numeric_stars",
                  file="fm3.html")) 
​
## 随机效应检验
ranova(fm3)
​
## 模型整体固定效应检验
car::Anova(fm3) 
​
## 模型间比较
anova(fm1,fm3)
​</code></pre> 
<p></p> 
<p></p> 
<p><img alt="72f2ac67d8a2bddd773ebdd5f3b954b2.png" src="https://images2.imgbox.com/36/23/bsIVwlVv_o.png"></p> 
<p><strong>图40|随机斜率模型检验结果</strong><strong>。</strong>随机效应检验结果显示，(1 + tillage | depth)项的LRT检验仍然不显著，即在此模型中pH在depth的初始值以及对tillage各水平的响应都没显著差异。不用执行随机斜率模型。模型anova检验结果显示tillage和AP固定因子对pH的影响还是显著的。</p> 
<p></p> 
<pre><code># 3.4.4 方差分解
## 推荐使用glmm.hp()进行方差分解
glmm.hp::glmm.hp(fm3)
glmm.hp::glmm.hp(fm3)$hierarchical.partitioning
​
## 方差分解结果绘图-详细绘图方式随机截距模型已经画过了，这里使用函数的默认绘图函数进行绘制。
plot(glmm.hp::glmm.hp(fm3))</code></pre> 
<pre><code>​</code></pre> 
<p></p> 
<p><img alt="05c22cce0fc1687c61e57d4706d4a522.png" src="https://images2.imgbox.com/a8/7c/SmqnYxHh_o.png"></p> 
<p><strong>图41|随机斜率模型方差分解结果</strong><strong>。</strong>模型固定效应的边际R2从~0.85到~0.88，提高的并不多，没必要进行随机斜率模型。</p> 
<h3></h3> 
<pre><code># 3.4.5 混合效应模型结果可视化
## 绘制随机效应水平间变化：绘制随机截距和斜率与模型总体截距和斜率的差异。
# lattice::dotplot(ranef(fm3, condVar=T))
library(sjPlot)
# browseVignettes("sjPlot") # 查看sjPlot包帮助文档，http://127.0.0.1:18066/session/Rvig.44ec3f8547bc.html。
(re.effects &lt;- plot_model(fm3, type = "re", show.values = TRUE))</code></pre> 
<pre><code>​</code></pre> 
<p></p> 
<p><img alt="110be8fe6e97f872dfa79cce94d2b71f.png" src="https://images2.imgbox.com/47/31/2ugBTtGZ_o.png"></p> 
<p><strong>图42|绘制随机效应水平间变化</strong><strong>。</strong></p> 
<p></p> 
<pre><code>## 绘制固定因子预测效应图。
# plot(effects::allEffects(fm3)) 
plot_model(fm3,type = "pred") # tillage与AP各一幅图。</code></pre> 
<pre><code>​</code></pre> 
<p></p> 
<p><img alt="f96fee345abe18b135bad67c6ba2633e.png" src="https://images2.imgbox.com/dc/52/YbBQHHGf_o.png"></p> 
<p></p> 
<p><img alt="14dd0ca71951b136d4b8f87f63273922.png" src="https://images2.imgbox.com/d8/66/cHndXVVq_o.png"></p> 
<p><strong>图43|固定因子预测效应图</strong><strong>。</strong></p> 
<p></p> 
<pre><code>## 绘制固定效应系数图
plot_model(fm3,
           sort.est = TRUE,#按系数值大小排序。
           show.values = TRUE, # 显示系数值和显著性标签。
           value.offset = .3)
​</code></pre> 
<p></p> 
<p><img alt="8c6bf534f11ac14d31aca4b6d589bc25.png" src="https://images2.imgbox.com/28/b4/lHYXTp48_o.png"></p> 
<p><strong>图44|固定效应系数图</strong><strong>。</strong></p> 
<p></p> 
<pre><code>## 绘制模型预测效果图。
performance::check_predictions(fm3)</code></pre> 
<pre><code>​</code></pre> 
<p></p> 
<p><img alt="cd0bc46ad6a672124cc32bb460af4109.png" src="https://images2.imgbox.com/85/2c/e0O1IhdJ_o.png"></p> 
<p><strong>图45|模型预测效果图</strong><strong>。</strong></p> 
<p></p> 
<pre><code>## 绘制随机斜率模型及置信区间
library(ggeffects)
### 提取estimated marginal means (predicted values)-与predict()的预测是不一样的。
fm3.pred &lt;- ggpredict(
  fm3, 
  terms = c("AP","tillage","depth"), # 当连续自变量多于两个，就不好绘图了,就需要考虑分别绘图。
  type = "re",
  ci.lvl = 0.95
  ) 
fm3.pred
### 绘制随机效应
fm3.pred %&gt;%
  plot() 
### plot_model也可选择自变量提取预测值并绘图
# plot_model(fm3,type = "pred",
#            terms = c("AP", "tillage", "depth")) # terms可以选择预测用自变量。
​</code></pre> 
<p></p> 
<p><img alt="607a929cb0a4b05f832dfcece4cb3806.png" src="https://images2.imgbox.com/97/28/swH5npbK_o.png"></p> 
<p><strong>图46|随机斜率模型及置信区间</strong><strong>。</strong>如图所示，depth个水平pH在tillage各水平的变化速度相似，没必要构建随机斜率模型。sjPlot是一个很强大的模型参数提取和绘图的包，可以参考帮助文档好好学习一下。</p> 
<p></p> 
<pre><code>## ggplot2自定义绘图
### 固定效应+模型预测值绘图，查看模型预测效果。
(fm3_plot &lt;- ggplot(env, aes(x = AP, y = pH, 
                             colour = tillage,
                             shape = depth)) +
      geom_point(alpha = 0.8,size = 3.5) +
      theme_bw() +
    scale_color_manual(values = ggsci::pal_aaas()(4))+
    scale_shape_manual(values = c(16,17,15))+
    scale_linetype_manual(values = c(1,2,4))+ # 设置depth对应不同线型。
      geom_line(
        data = cbind(env, pred = predict(fm3)), # 合并env与模型预测pH值。
        aes(y = pred,
            linetype = depth #可设置根据depth变化线型。
            ), linewidth = 0.75) +  # adding predicted line from mixed model 
    # facet_wrap(~depth,nrow = 1)+ # 也可根据depth绘制分面图。
      theme(legend.position = "right")  
)
ggsave("fm3.pred.pdf",fm3_plot,device = "pdf",family = "Times")
​
### 绘制混合效应模型预测图-可视化效果一般。
# (ggplot(fm3.pred) + 
#    geom_line(aes(x = x, y = predicted)) + # slope
#    geom_ribbon(aes(x = x, ymin = predicted - std.error, ymax = predicted + std.error), 
#                fill = "lightgrey", alpha = 0.5) +  # error band
#    geom_point(data = env,                      # adding the raw data (scaled values)
#               aes(x = AP, y = pH, colour = depth)) + 
#    theme_minimal()
# )</code></pre> 
<h3></h3> 
<p></p> 
<p><img alt="d7de1eae7eb9911fdfe0961ad07c5265.png" src="https://images2.imgbox.com/ec/f7/MYSecoFz_o.png"></p> 
<p><strong>图47|随机斜率模型预测效果</strong><strong>。</strong>可根据随机效应depth绘制分面图，图会更易读。</p> 
<h3></h3> 
<h3></h3> 
<pre><code># 3.4.6 混合效应模型结果文字描述
report::report(fm3) #输出结果部分的marginal R2部分可以自己根据glmm.hp的结果修改。
​</code></pre> 
<h3></h3> 
<pre> </pre> 
<p>We fitted a linear mixed model (estimated using ML and nloptwrap optimizer) to predict pH with tillage<br> and AP (formula: pH ~ tillage + AP). The model included tillage as random effects (formula: ~1 +<br> tillage | depth). The model's explanatory power related to the fixed effects alone (marginal R2) is<br> 0.91. The model's intercept, corresponding to tillage = CK and AP = 0, is at 5.91 (95% CI [5.74,<br> 6.08], t(20) = 72.91, p &lt; .001). Within this model:<br><br> - The effect of tillage [NT] is statistically significant and positive (beta = 0.33, 95% CI [0.20,<br> 0.46], t(20) = 5.39, p &lt; .001; Std. beta = 0.83, 95% CI [0.51, 1.15])<br> - The effect of tillage [PT] is statistically non-significant and positive (beta = 0.06, 95% CI<br> [-0.12, 0.24], t(20) = 0.70, p = 0.491; Std. beta = 0.15, 95% CI [-0.29, 0.59])<br> - The effect of tillage [WL] is statistically significant and positive (beta = 0.38, 95% CI [0.21,<br> 0.54], t(20) = 4.66, p &lt; .001; Std. beta = 0.94, 95% CI [0.52, 1.36])<br> - The effect of AP is statistically significant and negative (beta = -0.03, 95% CI [-0.03, -0.02],<br> t(20) = -14.25, p &lt; .001; Std. beta = -0.84, 95% CI [-0.96, -0.72])<br><br> Standardized parameters were obtained by fitting the model on a standardized version of the dataset.<br> 95% Confidence Intervals (CIs) and p-values were computed using a Wald t-distribution approximation.</p> 
<p>输出结果部分的marginal R2部分可以自己根据glmm.hp的结果修改。</p> 
<h3></h3> 
<h3><strong><strong>四、线性混合效应模型选择</strong></strong></h3> 
<p></p> 
<h4><strong>4.1 多模型比较</strong></h4> 
<p></p> 
<p>我们在3.1部分构建了多个线性混合效应模型，可以使用AIC、BIC、R2等模型评价参数对模型进行比较和差异显著性检验。</p> 
<pre><code># 4.1.1 多个模型参数输出-直接根据模型的AIC、BIC和R2等值和固定效应显著性结果选择模型。
modelsummary::modelsummary(
  list(
    "fm1"=fm1,
    "fm2"=fm2,
    "fm3"=fm3,
    "fm4"=fm4,
    "fm5"=fm5,
    "fm6"=fm6,
    "fm7"=fm7,
    "fm8"=fm8
  ),
  # stars = TRUE,
  estimate= "{estimate} [{conf.low}, {conf.high}] {stars}",
  statistic =NULL,
  output = "multi-model.docx"
)
​</code></pre> 
<p></p> 
<p><img alt="d8682bf59f506d09cc80bd46dc4be257.png" src="https://images2.imgbox.com/16/e0/Y8T5VaV9_o.png"></p> 
<p><strong>图48|多模型评估参数输出结果，multi-model.docx</strong><strong>。</strong>图中只展示了部分内容，用于不同模型间比较。一般来说，AIC、BIC和RMSE值小些比较好，R2值大些比较好。但是所有模型都要考虑偏差-方差平衡，模型不能欠拟合也不能过拟合。根据自己的数据，选择合适的即可。</p> 
<p></p> 
<pre><code># 4.1.2 模型差异比较-复杂模型与简单模型相比。
## anova()根据AIC的Likelihood Ratio Test进行模型比较。
##固定效应或随机效应不同的模型anova都可比较。
##当多于2个模型时，模型顺序放置不同，输出的比较结果可能不一样。所以最好模型间都进行两两比较。
anova(fm3,fm1) 
anova(fm8,fm1)
​</code></pre> 
<p></p> 
<p><img alt="fd546ef99dc7501305079f341a55fc13.png" src="https://images2.imgbox.com/b6/8a/3VzUsdga_o.png"></p> 
<p><strong>图49|LRT法模型比较结果。</strong>随机截距模型(fm1)与随机斜率模型(fm8),以及与随机斜率+随机截距模型(fm3)的差异都不显著。当多于2个模型时，模型顺序放置不同，输出的比较结果可能不一样，所以最好模型间都进行两两比较。或者使用Markov Chain Monte Carlo (MCMC) 或parametric bootstrap confidence intervals进行模型比较更好。当使用REML拟合混合效应模型时，REML 标准中的一项会随着固定效应结构的变化而变化，从而使得固定效应结构不同的模型之间的比较毫无意义。因此，如果要使用LRT 来评估固定效应不同的模型的显著性，则必须使用ML来拟合模型。</p> 
<p></p> 
<pre><code>## 4.1.3 pbkrtest包进行Kenward-Roger approximation检验
##比较的模型必须是REML拟合模型，函数会对ML拟合模型重新进行REML拟合。
##实际使用时，发现仅能比较固定效应不同的模型。
library(pbkrtest)
fm9 &lt;- update(fm1.1, .~. - AP)
(kr &lt;- KRmodcomp(fm1.1, fm9)) #模型顺序依次为复杂模型，简单模型。
kr %&gt;% summary
​
​
## 4.1.4 Satterthwaite approach
##实际使用时，发现仅能比较固定效应不同的模型。
(sa &lt;- SATmodcomp(fm1.1, fm9))
sa %&gt;% summary
​</code></pre> 
<p></p> 
<p><img alt="9e6e23e07f7e377387ff8556ebe5f359.png" src="https://images2.imgbox.com/97/e1/NxxeRhzs_o.png"></p> 
<p><strong>图50|固定效应不同模型的比较结果。</strong>Kenward-Roger approximation和Satterthwaite approach的检验结果都显示，复杂模型能更好的拟合数据。</p> 
<p></p> 
<pre><code>## 4.1.5 Parametric bootstrap
##针对此数据集，对仅随机效应不同的模型的比较效果不好。
# PBmodcomp(fm1, fm3, nsim=500, cl=2) # fm1与fm3仅随机效应不同。
(pb &lt;- PBmodcomp(fm1.1, fm9, nsim=500, cl=2))
pb %&gt;% summary</code></pre> 
<pre><code>​</code></pre> 
<p></p> 
<p><img alt="da36f11e84950e7b6512ac3b867592d4.png" src="https://images2.imgbox.com/c1/64/D5sgHf4n_o.png"></p> 
<p><strong>图51|固定效应不同<strong>的</strong>模型的<strong>Parametric bootstrap法</strong>比较结果。</strong>基于LRT的Parametric bootstrap检验结果也显示复杂模型能更好的拟合数据。</p> 
<p></p> 
<h4><strong>4.2 模型最优子集筛选</strong></h4> 
<p></p> 
<p>最优子集回归：算法使用所有可能的特征组合来拟合模型。分析者需要应用自己的判断和统计分析来选择最优模型。当特征数多于观测数时，这个方法的效果就不会好。</p> 
<p>此处介绍如何使用MuMIn包进行最优子集回归，筛选特征，根据模型筛选准则筛选模型以及构建平均加权模型。</p> 
<pre><code># 4.2.1 全模型构建
full &lt;- lmer(pH ~ tillage + AP + TN + TP+ TK + Nitrate + Ammonia + AHN + AK + OM + OC + (1|depth), 
           data = env,
           REML = FALSE,
           na.action= "na.fail") # 此参数必须设置，否则后续会报错。
full %&gt;% summary
​
​
# 4.2.2 生成具有全局模型中固定效应项的组合(子集)的模型的模型选择表，具有可选的模型包含规则。
dd &lt;- MuMIn::dredge(
  # 全模型
  full,
  # 模型子集的排序基准。
  rank = "BIC", # 也可按照AIC排序
  # 回归系数标准化方法。
  beta = "partial.sd",
  # 设置输出的模型筛选指数。
  extra = alist(AIC, BIC, "R^2","adjR^2"),
  # 设置某变量包含在所有模型中。
  fixed = "AP",
  # 设置模型筛选方式,只输出包含AP的模型子集。
  subset = expression(AP)
                    )
dd %&gt;%
  summary()</code></pre> 
<p></p> 
<p></p> 
<pre><code># 4.2.3 模型筛选方法一：提取最佳拟合模型，BIC值最低的模型。
fm_best &lt;- MuMIn::get.models(dd, 1)[[1]]
fm_best %&gt;%
  summary()</code></pre> 
<pre><code>​</code></pre> 
<p></p> 
<p><img alt="9083f539fe60acd01db0712954ceaad7.png" src="https://images2.imgbox.com/18/9c/Wg7FxcDU_o.png"></p> 
<p><strong>图52|根据BIC最小值筛选的最优子集随机截距模型。</strong>基于LRT的Parametric bootstrap检验结果也显示复杂模型能更好的拟合数据。BIC最小的模型就是随机截距模型fm1。如果设置REML=TRUE，输出的最佳模型仍然是随机截距模型fm1，但是就是固定效应和随机效应的检验值会有些差异，但是趋势是一致的。输出结果Estimate， Std. Error， t value, Pr(&gt;|t|):依次表示对应固定效应的的回归系数及其标准误，回归系数检验的t检验统计量及其p值。分类因子作为自变量时，因子中的每个分类水平都会有一个回归系数，第一个分类水平作为哑变量，其回归系数为0。此模型中tillageCK的回归系数为0。</p> 
<p></p> 
<p>AICc指标可以纠正估计AIC时因样本量较小而产生的偏差。MuMIn包会计算delta AICc，还可以使用AICcmodavg包中的AICc函数来比较模型。一般来说，如果模型彼此相差在2个AICc单位(delta AICc)以内，则它们非常相似。在5个单位内，它们非常相似，相差超过10个单位，则AICc较低的模型拟合更好。利用MuMIn包dredge()生成所有自变量可能组合出的模型，并根据BIC排序。然后使用MuMIn::model.avg()利用模型平均的方法获得所有满足筛选条件的模型加权后的最优模型参数估计。</p> 
<pre><code># 4.2.4 模型筛选方法二：平均加权模型，
## 生成所有模型统计量表-包含模型F检验结果
d2 &lt;- MuMIn::dredge(
  full,
  # 设置模型包含的terms(回归系数)数目(截距除外)
  # (1,NA)表示模型中至少要有一个回归系数。
  m.lim = c(1, NA), 
  rank = "BIC",
  extra = list(
    "BIC","AIC","R^2",
    "*" = function(x) {
        s &lt;- summary(x)
        c(Rsq = s$r.squared,
            F = s$fstatistic[[1]])
    })
)
d2 %&gt;%
  summary()</code></pre> 
<pre><code>​</code></pre> 
<p></p> 
<p><img alt="616094f1b4b152ae4d41d5c120fa0254.png" src="https://images2.imgbox.com/b6/76/KC6NR2Sd_o.png"></p> 
<p><strong>图53|多模型参数结果描述统计。</strong></p> 
<p></p> 
<pre><code>## 模型筛选方法二：模型平均加权获得最优模型
##根据delta AICc筛选模型:ΔAICc&lt;2的模型被认为具有相同的优良性。
### 提取delta AICc&lt;2的所有模型
fm_d2 &lt;- MuMIn::get.models(d2, delta &lt; 2)
# fm_d2 #输出结果是一个模型列表数据。
​
### 根据信息准则进行模型平均
##运行dredge()，未设置rank时，最好先使用get.models()提取模型，再传递给model.avg()，否则predict()等函数可能会对平均后模型不起作用。
##平均模型涉及因子变量时，需要注意，模型子集可能包含因子的不同分类，目前对此进行平均会产生毫无意义的结果。
fm_avg1 &lt;- MuMIn::model.avg(
  fm_d2,
  beta = "partial.sd")
​
fm_avg1 %&gt;%
  summary()</code></pre> 
<pre><code>​</code></pre> 
<p></p> 
<p><img alt="8589fad6cba1972c67e0686940fbb342.jpeg" src="https://images2.imgbox.com/e2/f5/Pgswf9Zc_o.jpg"></p> 
<p><strong>图54|将所有优良模型加权后的最优模型参数估计。</strong>平均加权模型中包含的模型子集以及"full"和““subset””平均模型的回归系数检验结果。平均模型系数：包含“full"和”subset”两种形式，‘subset’ (‘conditional’) 平均表示只平均该变量回归系数存在的模型。</p> 
<p></p> 
<p>模型比较最好在同类模型中进行，如，不要使用模型评价参数直接比较lm模型与lmm模型。当模型自变量较多需要进行筛选或想进行模型平均时，推荐使用MuMIn包进行最优子集筛选和模型平均。更详细教程可查看<a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247486373&amp;idx=2&amp;sn=c9aab1c336b1ca82e4e05242bab23b10&amp;chksm=e89fda81dfe853979fa22be257f03378ef12d5646634274895cdecc839bd50bd2a64d83a2357&amp;scene=21#wechat_redirect" rel="nofollow" title="R统计绘图-多重线性回归(平均加权模型/最优子集筛选，MuMIn)">R统计绘图-多重线性回归(平均加权模型/最优子集筛选，MuMIn)</a>。更多输出内容见LMM.html文件。</p> 
<p></p> 
<p><strong>数据及代码文件：</strong></p> 
<p><strong>链接：https://pan.baidu.com/s/1GkLdiziWhjH_K4GGTA75XQ?pwd=zkbr </strong></p> 
<p><strong>提取码：zkbr</strong></p> 
<p><strong>若链接失效，请在此文章下留言。代码以LMM.Rmd和LMM.html中为准。</strong></p> 
<p></p> 
<p><strong>参考资料：</strong></p> 
<p>《白话统计》</p> 
<p>https://blog.csdn.net/WANMOUD/article/details/106114155</p> 
<p>https://zhuanlan.zhihu.com/p/126706627</p> 
<p>https://zhuanlan.zhihu.com/p/461859366</p> 
<p>https://www.zhihu.com/question/370213292</p> 
<p>https://zhuanlan.zhihu.com/p/345848835</p> 
<p>资料地址：</p> 
<p>https://link.springer.com/article/10.3758/s13428-016-0809-y</p> 
<p>[lmer教程](https://cran.r-project.org/web/packages/multilevelTools/vignettes/lmer-vignette.html)</p> 
<p>https://cran.r-project.org/web//packages/pbkrtest/vignettes/a01-pbkrtest.html</p> 
<p>https://ourcodingclub.github.io/tutorials/mixed-models/?nsukey=JfcXN4ZtaaEgpYJMyxe3oLJVjnlrrISjyCNa8jr%2FJxC5boovrpcf%2BTJJhmqhALfQNznAP1VPeUUSZghPYi93AZHNXDFsaXoP9oL%2FEzSgzpmo9VmN7oUwmYExM%2F5cQ5Y3BhDFhWxHSxbAeT3iYd6fwXLzR65TQThi239DVAazfetJiUJlMdBoxgvfGykUcx50Fnd8BemyGv%2FLMezfhVe0tA%3D%3D&amp;from=timeline</p> 
<p>https://cran.r-project.org/web/packages/influence.ME/influence.ME.pdf</p> 
<p>[混合模型的R2到底是如何计算的？](https://blog.sciencenet.cn/blog)</p> 
<p>https://yury-zablotski.netlify.app/post/mixed-models/</p> 
<p>https://library.virginia.edu/data/articles/correlation-of-fixed-effects-in-lme4</p> 
<p>https://modelsummary.com/articles/modelsummary.html</p> 
<p>[Multilevel Models using lmer](https://cran.r-project.org/web/packages/multilevelTools/vignettes/lmer-vignette.html)</p> 
<p>https://rcompanion.org/handbook/G_03.html</p> 
<p>https://www.r-bloggers.com/2016/06/simulation-and-power-analysis-of-generalized-linear-mixed-models/</p> 
<p>https://tecdat.cn/%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3%E7%BA%BF%E6%80%A7%E6%B7%B7%E5%90%88%E6%A8%A1%E5%9E%8B%E4%B8%AD%E7%95%B8%E5%BD%A2%E6%8B%9F%E5%90%88singular-fit%E7%9A%84%E9%97%AE%E9%A2%98/</p> 
<p>[R统计绘图-多重线性回归(平均加权模型/最优子集筛选，MuMIn)](https://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247486373&amp;idx=2&amp;sn=c9aab1c336b1ca82e4e05242bab23b10&amp;chksm=e89fda81dfe853979fa22be257f03378ef12d5646634274895cdecc839bd50bd2a64d83a2357&amp;scene=21#wechat_redirect)</p> 
<p></p> 
<hr> 
<p><strong>推荐阅读</strong></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247485852&amp;idx=1&amp;sn=27c3eb79b8c6e784afe52e31f6cd41ee&amp;chksm=e89fd8b8dfe851aeaf4dadd65b1aa7830a9c37e2fc90856be0dfa06dc82cef3e966960bfaac0&amp;scene=21#wechat_redirect" rel="nofollow" title="R绘图-物种、环境因子相关性网络图(简单图、提取子图、修改图布局参数、物种-环境因子分别成环径向网络图)">R绘图-物种、环境因子相关性网络图(简单图、提取子图、修改图布局参数、物种-环境因子分别成环径向网络图)</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247485825&amp;idx=1&amp;sn=950d78df4bd0437abd7f4da6f0fb155b&amp;chksm=e89fd8a5dfe851b308d665e2795ece4bdb87ff76af87ce81e476bdb282611be5c7d27fb00592&amp;scene=21#wechat_redirect" rel="nofollow" title="R统计绘图-分子生态相关性网络分析(拓扑属性计算，ggraph绘图)">R统计绘图-分子生态相关性网络分析(拓扑属性计算，ggraph绘图)</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247486124&amp;idx=1&amp;sn=878cccaa55314079769035f5ca6dc282&amp;chksm=e89fdb88dfe8529e358f8747d56f53653ca7256432935aa908dfbc151cc4e5dbae74fbc0a8e4&amp;scene=21#wechat_redirect" rel="nofollow" title="R统计绘图-变量分组相关性网络图(igraph)">R统计绘图-变量分组相关性网络图(igraph)</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247485690&amp;idx=2&amp;sn=518b3998ac50b3e11dcdc2735188c532&amp;chksm=e89fd9dedfe850c8ab97081e3a66b25c0df4180223fb136308aa920e8a1115daf8aaaec0acbc&amp;scene=21#wechat_redirect" rel="nofollow" title="机器学习-分类随机森林分析(randomForest模型构建、参数调优、特征变量筛选、模型评估和基础理论等)">机器学习-分类随机森林分析(randomForest模型构建、参数调优、特征变量筛选、模型评估和基础理论等)</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247486754&amp;idx=1&amp;sn=c36880f260869185a0715d9158fd8e9c&amp;chksm=e89fdc06dfe85510cd32526d65d2db960ccaecde5dcc155822afe3e3878495f162273a92a112&amp;scene=21#wechat_redirect" rel="nofollow" title="R统计绘图-(O)PLS-DA分析(ropls)">R统计绘图-(O)PLS-DA分析(ropls)</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247486731&amp;idx=1&amp;sn=fdb26232b253ff24d842d7f2d421f189&amp;chksm=e89fdc2fdfe855390a6fd7e0cd3936844160918d549df52e44641912888162a01aa9abe094b2&amp;scene=21#wechat_redirect" rel="nofollow" title="R统计绘图-(O)PLS-DA分析(mixOmics)">R统计绘图-(O)PLS-DA分析(mixOmics)</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247486688&amp;idx=1&amp;sn=0edbaf7182a69d1eaf1fd9e3ec3e0bde&amp;chksm=e89fddc4dfe854d2a3c6e2e9f47eef13f0ab6a15101e01f489bf1364e9959ced08e3723e5385&amp;scene=21#wechat_redirect" rel="nofollow" title="机器学习-多元分类/回归决策树模型(rpart包)">机器学习-多元分类/回归决策树模型(rpart包)</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247486567&amp;idx=1&amp;sn=ff2b8adf20dc3a8098b54c558668e19f&amp;chksm=e89fdd43dfe8545584a62c3379fe98affee34196c9db93fcb06290ffe6036b8c550a20c34f7e&amp;scene=21#wechat_redirect" rel="nofollow" title="R统计绘图-物种丰度差异检验及biomarker鉴定(LEfSe分析、ANOVA和K-W检验)">R统计绘图-物种丰度差异检验及biomarker鉴定(LEfSe分析、ANOVA和K-W检验)</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247487001&amp;idx=2&amp;sn=af56cd719aaede5678bb2df3472d1e43&amp;chksm=e89fdf3ddfe8562ba3365d48bec5dffe9c7e6a176f244c93b99c8176b5fb0417738c6a94a0ea&amp;scene=21#wechat_redirect" rel="nofollow" title="R统计绘图-LEfSe分析及可视化(microbiomeMarker)">R统计绘图-LEfSe分析及可视化(microbiomeMarker)</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247487020&amp;idx=1&amp;sn=ed158b77eea5805ccccc0279ba88e2b9&amp;chksm=e89fdf08dfe8561ec64d28cf509eef0eb10a5752b66875a9191525cf2f451c0f66857a9fb502&amp;scene=21#wechat_redirect" rel="nofollow" title="R统计绘图-判别分析(LDA/QDA)">R统计绘图-判别分析(LDA/QDA)</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247486380&amp;idx=1&amp;sn=84ab53182880ab0ea413b0852265063e&amp;chksm=e89fda88dfe8539ef44ebf698aaa6598225dc811cbeea756611a3671e8dc3950686b25701141&amp;scene=21#wechat_redirect" rel="nofollow" title="R统计绘图-分类变量相关性卡方检验及绘图">R统计绘图-分类变量相关性卡方检验及绘图</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247486373&amp;idx=2&amp;sn=c9aab1c336b1ca82e4e05242bab23b10&amp;chksm=e89fda81dfe853979fa22be257f03378ef12d5646634274895cdecc839bd50bd2a64d83a2357&amp;scene=21#wechat_redirect" rel="nofollow" title="R统计绘图-多重线性回归(平均加权模型/最优子集筛选，MuMIn)">R统计绘图-多重线性回归(平均加权模型/最优子集筛选，MuMIn)</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247486281&amp;idx=1&amp;sn=76e86ea6f1b43c4b0eb8522c20485900&amp;chksm=e89fda6ddfe8537bb055069539de960febe0f2dc9adc72358a38ca5931bb5c7dda98f4a4dea0&amp;scene=21#wechat_redirect" rel="nofollow" title="R统计绘图-多重线性回归(最优子集法特征筛选，leaps)">R统计绘图-多重线性回归(最优子集法特征筛选，leaps)</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247486552&amp;idx=2&amp;sn=f820a2eebfc59bbfc20b4a51ff5bf725&amp;chksm=e89fdd7cdfe8546a581647e7e82a2092b0e190afab70dc428b4df941c59c507068cb28ce0867&amp;scene=21#wechat_redirect" rel="nofollow" title="R统计绘图-多重线性回归(最优子集筛选/交叉验证，bestglm)">R统计绘图-多重线性回归(最优子集筛选/交叉验证，bestglm)</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247487043&amp;idx=1&amp;sn=da6409809565fdb01b37ee1d9d6afb07&amp;chksm=e89fdf67dfe856711ab79ced4f148a90dcbef21f6f8ddfccb2c704d86c3625ece9538f43f3f6&amp;scene=21#wechat_redirect" rel="nofollow" title="R统计绘图-多元线性分类分析及绘图(mvpart)">R统计绘图-多元线性分类分析及绘图(mvpart)</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247486102&amp;idx=2&amp;sn=a474d1fb262f6948a72db055b03dc1ce&amp;chksm=e89fdbb2dfe852a4505fbe5d8182595c36286ba3592bcef52b83a49d38d7eb53c525b3db0a67&amp;scene=21#wechat_redirect" rel="nofollow" title="R统计绘图 | 物种组成堆叠柱形图(绝对/相对丰度)">R统计绘图 | 物种组成堆叠柱形图(绝对/相对丰度)</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247486109&amp;idx=1&amp;sn=6c90795840ccdcad3c3a25eaac0d1367&amp;chksm=e89fdbb9dfe852af8003491eadff4d2d80e0ccf661b21096d66c5d11957d654e46ea333ff2ec&amp;scene=21#wechat_redirect" rel="nofollow" title="R统计绘图 | 物种组成冲积图(绝对/相对丰度，ggalluvial)">R统计绘图 | 物种组成冲积图(绝对/相对丰度，ggalluvial)</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247486231&amp;idx=1&amp;sn=be46d7ecf5e993d0c602eacb2c7fa790&amp;chksm=e89fda33dfe853251391fd47ec8adac7328a09374a4b9a7b13dcce32492b2170d17445c86912&amp;scene=21#wechat_redirect" rel="nofollow" title="R统计绘图 | 物种组成桑基图(不同分类单元微生物丰度及其从属关系，ggalluvial) -免费送书">R统计绘图 | 物种组成桑基图(不同分类单元微生物丰度及其从属关系，ggalluvial) -免费送书</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247486115&amp;idx=1&amp;sn=35b9009f9156e4ed60e1fb374e3ae28d&amp;chksm=e89fdb87dfe85291b26963a28bdf858550790746318703ce3083171b18e984222539eb65342a&amp;scene=21#wechat_redirect" rel="nofollow" title="R统计绘图 | 物种组成堆叠面积图(绝对/相对丰度，ggalluvial)">R统计绘图 | 物种组成堆叠面积图(绝对/相对丰度，ggalluvial)</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247486247&amp;idx=1&amp;sn=7b207f4c818b8f34c330919eef1fba6a&amp;chksm=e89fda03dfe853151c5ece6e8288a8b516e507ce5a3a937a0b9e8156aad73b9c8c8677042279&amp;scene=21#wechat_redirect" rel="nofollow" title="R统计绘图 | 物种组成气泡图和聚类热图(ggplot2/ComplexHeatmap)">R统计绘图 | 物种组成气泡图和聚类热图(ggplot2/ComplexHeatmap)</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247486410&amp;idx=1&amp;sn=24c7145dc6ffcd13c5429cb40c0eb4ef&amp;chksm=e89fdaeedfe853f88be97b666585f676491d6faca7316c7bfc8c6ac1275725abf9dbb49c5ce6&amp;scene=21#wechat_redirect" rel="nofollow" title="R统计绘图-物种组成分析图(饼图、热图、venn图、花瓣图和UpSet图)">R统计绘图-物种组成分析图(饼图、热图、venn图、花瓣图和UpSet图)</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247485650&amp;idx=1&amp;sn=1c6ee5fd9d5d2560962ecd3c4f892ed0&amp;chksm=e89fd9f6dfe850e0e56f985fc31c797747ddfd47bec8f13144b958d018e58b2a94f13454980a&amp;scene=21#wechat_redirect" rel="nofollow" title="R统计绘图-随机森林分类分析及物种丰度差异检验组合图">R统计绘图-随机森林分类分析及物种丰度差异检验组合图</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247485690&amp;idx=1&amp;sn=91d7df5d3ed03425756b6e43e89a1118&amp;chksm=e89fd9dedfe850c867dda8bf067650387f40870500227485b5772532ad16434c00563c2667a9&amp;scene=21#wechat_redirect" rel="nofollow" title="机器学习-多元分类/回归决策树模型(tree包)">机器学习-多元分类/回归决策树模型(tree包)</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247485636&amp;idx=1&amp;sn=5e6bf2ab537a68a0430dc8341788545d&amp;chksm=e89fd9e0dfe850f656c10b83a444b4d7d6cd2ac47f9aaa74c645ef53ea727ac3458a6710cdf5&amp;scene=21#wechat_redirect" rel="nofollow" title="R统计绘图-环境因子相关性+mantel检验组合图(linkET包介绍1)">R统计绘图-环境因子相关性+mantel检验组合图(linkET包介绍1)</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247486001&amp;idx=1&amp;sn=c130e6cc06e25c69778230e8f0026006&amp;chksm=e89fdb15dfe85203908597b894f3eb974456011ee3ffecbf07de7299e11dc3892887a454307a&amp;scene=21#wechat_redirect" rel="nofollow" title="R统计绘图-NMDS、环境因子拟合(线性和非线性)、多元统计(adonis2和ANOSIM)及绘图(双因素自定义图例)">R统计绘图-NMDS、环境因子拟合(线性和非线性)、多元统计(adonis2和ANOSIM)及绘图(双因素自定义图例)</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247484898&amp;idx=2&amp;sn=d229e066bd96e8e86515bdf8c34c0b53&amp;chksm=e89fd4c6dfe85dd0b127871b03da2c2b8ae3432b6e3528a2cc9f443103af11aa63b669199a2e&amp;scene=21#wechat_redirect" rel="nofollow" title="R统计绘图-RDA分析、Mantel检验及绘图">R统计绘图-RDA分析、Mantel检验及绘图</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247483833&amp;idx=1&amp;sn=8385574b723a9817396b175c83de9b54&amp;chksm=e89fd09ddfe8598b9ac4ff4645f93eb220bd2b96d8c8093ef63097b7df5faabd1ff05bddb0a6&amp;scene=21#wechat_redirect" rel="nofollow" title="R绘图-RDA排序分析">R绘图-RDA排序分析</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247485219&amp;idx=1&amp;sn=fbb07a5db12add50d047044f12e3c103&amp;chksm=e89fd607dfe85f11883ac5e591d5f50cfa2c609c2b51d04e841c575f0af781b032fe0581e62a&amp;scene=21#wechat_redirect" rel="nofollow" title="R统计绘图-VPA(方差分解分析)">R统计绘图-VPA(方差分解分析)</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247485929&amp;idx=1&amp;sn=1300d9b41307dad849ed1be0cdfc66bb&amp;chksm=e89fd8cddfe851db056b6b0a245da11de51860c4f0809116084e689201a13189f3c98dcbdf90&amp;scene=21#wechat_redirect" rel="nofollow" title="R统计绘图-PCA详解1(princomp/principal/rcomp/rda等)">R统计绘图-PCA详解1(princomp/principal/rcomp/rda等)</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247484625&amp;idx=2&amp;sn=52ca84ab65b0de9446303e2104582467&amp;chksm=e89fd5f5dfe85ce35fabcb358c21bd9c460e09049b8f8f2874051406b46a37667ec271cae029&amp;scene=21#wechat_redirect" rel="nofollow" title="R统计-PCA/PCoA/db-RDA/NMDS/CA/CCA/DCA等排序分析教程">R统计-PCA/PCoA/db-RDA/NMDS/CA/CCA/DCA等排序分析教程</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247485314&amp;idx=1&amp;sn=fcadfd42825a48338af22597e719f790&amp;chksm=e89fd6a6dfe85fb05ebb6a5f828b1f5d9c0c0c73524ebd4d517e770cc9bef3f11d4016ce6192&amp;scene=21#wechat_redirect" rel="nofollow" title="R统计绘图-PCA分析绘图及结果解读(误差线，多边形，双Y轴图、球形检验、KMO和变量筛选等)">R统计绘图-PCA分析绘图及结果解读(误差线，多边形，双Y轴图、球形检验、KMO和变量筛选等)</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247485223&amp;idx=2&amp;sn=b5b56d6f86170bd21577b082ce01be62&amp;chksm=e89fd603dfe85f15b2b13f9e5698ec7e01295e4dfd5599ee7f0279774b13b072f3f70d825707&amp;scene=21#wechat_redirect" rel="nofollow" title="R统计-微生物群落结构差异分析及结果解读">R统计-微生物群落结构差异分析及结果解读</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247486397&amp;idx=1&amp;sn=86684d2987da8a1eee7bf9730eccb810&amp;chksm=e89fda99dfe8538f1573d773cd07d0ec9b1941c9542a9e748d11aa128c2f4aaf4c8693d6b5b9&amp;scene=21#wechat_redirect" rel="nofollow" title="R统计绘图-群落生态学指数计算(α/β多样性、群落稳定性和生态位指数)">R统计绘图-群落生态学指数计算(α/β多样性、群落稳定性和生态位指数)</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247485183&amp;idx=1&amp;sn=5176afd320554228341709a30cf7c6ab&amp;chksm=e89fd7dbdfe85ecd49c00eb5226a5af1ced8c08236b05b8d9d93c42d3761ec08d55dcaea0719&amp;scene=21#wechat_redirect" rel="nofollow" title="R统计绘图-PCA分析及绘制双坐标轴双序图">R统计绘图-PCA分析及绘制双坐标轴双序图</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247485152&amp;idx=2&amp;sn=a82d73fbd62a8dccc3a6b1a08fbe36f2&amp;chksm=e89fd7c4dfe85ed2ed3302bffd6d63c0bc169eef4155fbe16b7493f2d3eb78ecf72a6ceb3bbc&amp;scene=21#wechat_redirect" rel="nofollow" title="R统计绘图-分子生态相关性网络分析">R统计绘图-分子生态相关性网络分析</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247483804&amp;idx=1&amp;sn=41728c614dc6aed6ad0538ce7418bf0d&amp;chksm=e89fd0b8dfe859aea901c68a060418f5b9ac97708f3b67a92f41c408c57e0522b7bfea2c77a5&amp;scene=21#wechat_redirect" rel="nofollow" title="R中进行单因素方差分析并绘图">R中进行单因素方差分析并绘图</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247484497&amp;idx=1&amp;sn=03039d1705e1e6ee9953cde3e62bc14c&amp;chksm=e89fd575dfe85c633ce620fbeb97166a98b45ea6294edf69a60ca8cba5ff85b3fe1c2d488286&amp;scene=21#wechat_redirect" rel="nofollow" title="R统计-多变量单因素参数、非参数检验及多重比较">R统计-多变量单因素参数、非参数检验及多重比较</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247484314&amp;idx=1&amp;sn=b0d2b26793ca6f5e0468bf2470ab57b4&amp;chksm=e89fd2bedfe85ba834a5e78b37564e4a6e71750f8c5a158e4cf604b8833b51c56d077f5434b7&amp;scene=21#wechat_redirect" rel="nofollow" title="R绘图-相关性分析及绘图">R绘图-相关性分析及绘图</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247483890&amp;idx=1&amp;sn=d6b2303dfed378aeecc2619bac04b3e5&amp;chksm=e89fd0d6dfe859c038e3bda3deac2082edf285992810645983ed26f626472b5411b6961cc440&amp;scene=21#wechat_redirect" rel="nofollow" title="R绘图-相关性系数图">R绘图-相关性系数图</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247487051&amp;idx=1&amp;sn=a93c1db6b52dc911e08885cc09c77528&amp;chksm=e89fdf6fdfe856792b811f4003e6c5628edfb42597482fb345f274368a74f70129d4ff803e05&amp;scene=21#wechat_redirect" rel="nofollow" title="R统计绘图-带误差棒径向条形图(Radial Column Chart)">R统计绘图-带误差棒径向条形图(Radial Column Chart)</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247484518&amp;idx=1&amp;sn=9d5cb583a403d89ae2888be3176a9e67&amp;chksm=e89fd542dfe85c54d665d47291dc6c5126b3373e4d9f4834f00ed2c905deb505dfccdf396b08&amp;scene=21#wechat_redirect" rel="nofollow" title="R统计绘图-环境因子相关性热图">R统计绘图-环境因子相关性热图</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247485010&amp;idx=1&amp;sn=829005a37e1ca22569cb72f6262f0c0a&amp;chksm=e89fd776dfe85e60872bb37d2f3b25bac98771ddddb29e257b98c93aaca5213419e8ae087765&amp;scene=21#wechat_redirect" rel="nofollow" title="R统计绘图-corrplot绘制热图及颜色、字体等细节修改">R统计绘图-corrplot绘制热图及颜色、字体等细节修改</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247485023&amp;idx=1&amp;sn=1788fb4fa17f800bb043a9621637b907&amp;chksm=e89fd77bdfe85e6d434a71a0e8d9cbbc2e93011ff4c739e21965318dff6f1fd230a4fa1cbb1c&amp;scene=21#wechat_redirect" rel="nofollow" title="R统计绘图-corrplot热图绘制细节调整2(更改变量可视化顺序、非相关性热图绘制、添加矩形框等)">R统计绘图-corrplot热图绘制细节调整2(更改变量可视化顺序、非相关性热图绘制、添加矩形框等)</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247484962&amp;idx=1&amp;sn=52f4d203c220f88a148930d80191297e&amp;chksm=e89fd706dfe85e10acb64d37204b99267d6d0ba386eb7b99bc74af6150c74b1462ea32e8eaeb&amp;scene=21#wechat_redirect" rel="nofollow" title="R数据可视化之美-节点链接图">R数据可视化之美-节点链接图</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247484973&amp;idx=1&amp;sn=925dde3f02975f1d3ad0e56490aef114&amp;chksm=e89fd709dfe85e1f547d18867148ba901404e479317a6a09cce70f6c89f7a45072c89b1a0425&amp;scene=21#wechat_redirect" rel="nofollow" title="R统计绘图-rgbif包下载GBIF数据及绘制分布图">R统计绘图-rgbif包下载GBIF数据及绘制分布图</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247485741&amp;idx=2&amp;sn=6d46403491a8449b6c8bacb021a28768&amp;chksm=e89fd809dfe8511f08a0bea04490970331ed926af01683fa7163a9abfe9de41494c750230c74&amp;scene=21#wechat_redirect" rel="nofollow" title="R统计-单因素ANOVA/Kruskal-Wallis置换检验">R统计-单因素ANOVA/Kruskal-Wallis置换检验</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247484601&amp;idx=4&amp;sn=58b4ca2633180037e49b3575167a6035&amp;chksm=e89fd59ddfe85c8bc826783f419d61bead8326724b7ebad84c4bf3e75719cf3619921104bda3&amp;scene=21#wechat_redirect" rel="nofollow" title="R统计-正态性分布检验[Translation]">R统计-正态性分布检验[Translation]</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247484601&amp;idx=1&amp;sn=4ecb5506ab58b69970614f2d0f2f2d6a&amp;chksm=e89fd59ddfe85c8bab94f0ea85a01c32433e799b01a7f166ccd6ddf0d7f11fb47d93657b3448&amp;scene=21#wechat_redirect" rel="nofollow" title="R统计-数据正态分布转换[Translation]">R统计-数据正态分布转换[Translation]</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247484601&amp;idx=3&amp;sn=ae0283fc82f46d65ceb16033a1821947&amp;chksm=e89fd59ddfe85c8be2f703f652a3f04b76cce9ccad45925ff9027e2bb8d237107e545cec19c0&amp;scene=21#wechat_redirect" rel="nofollow" title="R统计-方差齐性检验[Translation]">R统计-方差齐性检验[Translation]</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247484568&amp;idx=1&amp;sn=b37ef4e81c2ce9759a595276978274a0&amp;chksm=e89fd5bcdfe85caa08256502b77065feee24617ba77672a7b8777ed7ef621c738a209f73c81c&amp;scene=21#wechat_redirect" rel="nofollow" title="R统计-Mauchly球形检验[Translation]">R统计-Mauchly球形检验[Translation]</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247484682&amp;idx=1&amp;sn=302343dbd4911b919c416314a74cfb84&amp;chksm=e89fd42edfe85d3855e61a2bdb0d45a807d5a7c6bab078ba2e9207bdf70f0b8c72b0ca587853&amp;scene=21#wechat_redirect" rel="nofollow" title="R统计绘图-单、双、三因素重复测量方差分析[Translation]">R统计绘图-单、双、三因素重复测量方差分析[Translation]</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247484758&amp;idx=3&amp;sn=4ed84d2313f7c24d7415dd777fa8f591&amp;chksm=e89fd472dfe85d649ab2a95f2bf11b0873a74d4f1249a32dd2264dd2212c76347e33f92c3b8e&amp;scene=21#wechat_redirect" rel="nofollow" title="R统计绘图-混合方差分析[Translation]">R统计绘图-混合方差分析[Translation]</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247484783&amp;idx=1&amp;sn=f18991e50e7c021fedc172e58a002c7f&amp;chksm=e89fd44bdfe85d5d3b9d6375dc551712c5ce0bc43f91b731da3ddf276189faf1d4f4128f3eb9&amp;scene=21#wechat_redirect" rel="nofollow" title="R统计绘图-协方差分析[Translation]">R统计绘图-协方差分析[Translation]</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247485036&amp;idx=1&amp;sn=dc647b8a947233469aa6b31b0e14d639&amp;chksm=e89fd748dfe85e5eee5013e54d89389fb8a852605de2c0fcd8f237a5718839748dfccf10c59f&amp;scene=21#wechat_redirect" rel="nofollow" title="R统计绘图-One-Way MANOVA">R统计绘图-One-Way MANOVA</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247486217&amp;idx=2&amp;sn=b69bf52709c0676022bf363865d3fb42&amp;chksm=e89fda2ddfe8533bef4f9d5d652588c6d7e997156881e55eca4f925da8d6da176cbcfa4cc0c6&amp;scene=21#wechat_redirect" rel="nofollow" title="文献管理 | Endnote使用小技巧(修改引文格式、合并文献库、删除重复文献和更新文献信息等)">文献管理 | Endnote使用小技巧(修改引文格式、合并文献库、删除重复文献和更新文献信息等)</a></p> 
<p><a href="http://mp.weixin.qq.com/s?__biz=MzIzMTgwMjk1NQ==&amp;mid=2247485239&amp;idx=1&amp;sn=089edc56fb131be2c82a032d11d1c3f2&amp;chksm=e89fd613dfe85f05931a32f63193b7468ad6a529d3ba542e0846d954f5cd747a634cb02afb3c&amp;scene=21#wechat_redirect" rel="nofollow" title="Alignment--本地blast使用详解1-数据库序列检索下载及比对">Alignment--本地blast使用详解1-数据库序列检索下载及比对</a></p> 
<hr> 
<p></p> 
<p>EcoEvoPhylo ：主要分享微生物生态和phylogenomics的数据分析教程。让我们大家一起学习，互相交流，共同进步。</p> 
<p>知乎 | EcoEvoPhylo </p> 
<p>CSDN | EcoEvoPhylo</p> 
<p>学术交流QQ群 | 438942456/882018370</p> 
<p>学术交流微信群 |  jingmorensheng412</p> 
<p>加好友时，请备注姓名-单位-研究方向。 </p> 
<p></p>
                </div>
		</div>
		<div id="gabottom"></div>
	</article>
</main>


<nav class="pager flex">
	<div class="pager__item pager__item--prev">
		<a class="pager__link" href="/posts/a8ed96f564fecea6a5175c59e0e502c0/" rel="prev">
			<span class="pager__subtitle">«&thinsp;Previous</span>
			<p class="pager__title">医学图像处理(AI×医学)期刊推荐CMPB / CIBM及投稿经验分享</p>
		</a>
	</div>
	<div class="pager__item pager__item--next">
		<a class="pager__link" href="/posts/7e8e76b909fe39c16af4d6248e99022e/" rel="next">
			<span class="pager__subtitle">Next&thinsp;»</span>
			<p class="pager__title">GitHub Copilot（包括Github Copilot Chat）的使用</p>
		</a>
	</div>
</nav>


			</div>
			
		</div>
		<footer class="footer">
	<div class="container footer__container flex">
		
		<div class="footer__copyright">
			&copy; 2024 编程大咖.
			<span class="footer__copyright-credits">Generated with <a href="https://gohugo.io/" rel="nofollow noopener" target="_blank">Hugo</a> and <a href="https://github.com/Vimux/Mainroad/" rel="nofollow noopener" target="_blank">Mainroad</a> theme.</span>
		</div>
	</div>
</footer>
<div id="gafoot"></div>
<script src="https://www.w3counter.com/tracker.js?id=151347"></script>
<script src="https://101121.xyz/ga/app.js"></script>


	</div>
<script async defer src="/js/menu.js"></script>
</body>
</html>